### ISSUE TITLE
scripted doesn't work on 0.12.4

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#828]
### steps
1. use 0.13.0-RC3 launcher or 0.12.4 launcher.
2. set build.properties to `sbt.version=0.12.4`.
3. no cross building target 0.12 plugins.
4. run `scripted`.
### problem

```
sbt-assembly> scripted sbt-assembly/piecemeal
....
[trace] Stack trace suppressed: run last *:scripted for the full output.
[error] (*:scripted) java.lang.NoClassDefFoundError: jline/Terminal
[error] Total time: 6 s, completed Jul 26, 2013 3:23:47 AM
```

Here's the stack trace

```
java.lang.NoClassDefFoundError: jline/Terminal
  at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:112)
  at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:107)
  at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
  at sbt.test.ScriptedTests$.run(ScriptedTests.scala:108)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.invoke12$1(ScriptedPlugin.scala:54)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:56)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:53)
  at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
  at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
  at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
  at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
  at sbt.std.Transform$$anon$5.work(System.scala:71)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
  at sbt.Execute.work(Execute.scala:238)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
  at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassNotFoundException: jline.Terminal
  at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
  at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:112)
  at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:107)
  at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
  at sbt.test.ScriptedTests$.run(ScriptedTests.scala:108)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.invoke12$1(ScriptedPlugin.scala:54)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:56)
  at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:53)
  at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
  at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
  at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
  at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
  at sbt.std.Transform$$anon$5.work(System.scala:71)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
  at sbt.Execute.work(Execute.scala:238)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
  at java.lang.Thread.run(Thread.java:680)
```
### expectation

`scripted` runs.
### notes

`scripted` runs on 0.12.3 fine. Could this be a regression introduced by #781?

**Comment by earldouglas** [comment]
+1

**Comment by hamnis** [comment]
+1/2 suddenly it started working.. ish.

After the upgrade and running the scripted plugin, the input prompt disappears.

The history still works, but I cannot see what the command I am about to run, actually is.

According to @harrah this is due to incompatibilities with jline.

**Comment by earldouglas** [comment]
I noticed this too.  If you run `reset` at the command line, you should get your local echo back.

**Comment by rgladwell** [comment]
:+1:

**Comment by timperrett** [comment]
+1

**Comment by jozic** [comment]
+1

**Comment by hamnis** [comment]
any update on this?

**Comment by dwijnand** [comment]
0.12 is no longer relevant
