### ISSUE TITLE
"sbt '++ 2.13.0-M1!' compile" does not work with sbt 1.0.4

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#3771]
## steps

project/build.properties

```
sbt.version=1.0.4
```

build.sbt

```scala
scalaVersion := "2.13.0-M1"
```

Foo.scala

```scala
package example

class Foo
```

execute `sbt compile`

## problem

```
[info] Non-compiled module 'compiler-bridge_2.13.0-M2' for Scala 2.13.0-M1. Compiling...
/tmp/sbt_c64e77de/xsbt/Compat.scala:13: error: object shell is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.shell.ReplReporterImpl
                                   ^
/tmp/sbt_c64e77de/xsbt/Compat.scala:22: error: not found: type ReplReporterImpl
    new ReplReporterImpl(settings, writer)
        ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:12: error: object shell is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.shell.{ ILoop, ShellConfig, ReplReporterImpl }
                                   ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:42: error: not found: type ILoop
    val loop = new ILoop(ShellConfig(interpreterSettings)) {
                   ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:45: error: not found: type ReplReporterImpl
          val reporter = new ReplReporterImpl(interpreterSettings)
                             ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:46: error: not found: value intp
          intp = new IMain(interpreterSettings, reporter) {
          ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:51: error: not found: value intp
          intp.setContextClassLoader()
          ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:53: error: value createInterpreter is not a member of AnyRef
          super.createInterpreter(interpreterSettings)
                ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:56: error: not found: value intp
          intp.beQuietDuring(intp.bind(id, value.asInstanceOf[AnyRef].getClass.getName, value))
          ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:56: error: not found: value intp
          intp.beQuietDuring(intp.bind(id, value.asInstanceOf[AnyRef].getClass.getName, value))
                             ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:59: error: not found: value intp
          intp.interpret(initialCommands)
          ^
/tmp/sbt_c64e77de/xsbt/ConsoleInterface.scala:66: error: not found: value intp
          intp.interpret(cleanupCommands)
          ^
12 errors found
```

## expectation

compile success

## notes

sbt version: 1.0.4

This is a regression due to https://github.com/sbt/zinc/pull/453#discussion_r153066408
But I think this is not important issue because Scala 2.13.0-M1 is a old milestone version :)

**Comment by SethTisue** [comment]
I think it would be fine to close this as wontfix

**Comment by eed3si9n** [comment]
New Zinc with the fix was merged in #3816
