### ISSUE TITLE
`scalaHome` support is bitrotted, requires workaround to use with Scala 2.13

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#7477]
(and lord knows whether it works at all with Scala 3!)

If `scalaHome` didn't already exist, I'm not sure we would add it today, as it's not hard to just `publishLocal` from one's Scala 2 checkout (a method that I expect would also work for Scala 3).

I was able to get it partially working with Scala 2.13 by using a workaround, as follows.

I tried:

```
scalaVersion := "2.13.12"
scalaHome := Some(file("/Users/tisue/scala.213"))
```

(the doc is silent about how to handle `scalaVersion`, but we need to get the binary version right, at least; using e.g. `2.13.13-bin-SNAPSHOT"` seems to work just as well)

but then `console` gives:

```
[error] (scalaInstance) sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid:  (library jar  /Users/tisue/scala.213/lib/scala-library.jar)
```

there is no such `lib` directory in a Scala 2.13 checkout, but after `dist/mkPack`, `build/pack/lib/scala-library.jar` exists, so I thought maybe `ln -s build/pack/lib` would fix it, and it does get past the first error

and it doesn't make `console` work:

```
java.lang.NoSuchMethodError: 'org.jline.utils.AttributedString org.jline.utils.AttributedString.fromAnsi(java.lang.String, java.util.List, java.lang.String, java.lang.String)'
```

but it does make `compile` and `run` work:

```
% cat S.scala
object Main extends App {
  println(s"hi there! ${scala.util.Properties.versionNumberString}")
}
% sbt run
[info] welcome to sbt 1.9.8 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/tisue/tmp/scalaHome/project
[info] loading settings for project scalahome from build.sbt ...
[info] set current project to scalahome (in build file:/Users/tisue/tmp/scalaHome/)
[info] running Main 
hi there! 2.13.13-20240118-035212-951cc9b
```

so, the support isn't as fully bitrotted as I'd feared!

anyway, opening this issue to document the current state, but who knows, someone might take an interest in fixing it, and/or perhaps even adding Scala 3 support

**Comment by eed3si9n** [comment]
@SethTisue Thanks for the report!

**Comment by som-snytt** [comment]
I routinely set scalaHome to my build/pack.

I never use console, but it seems to work.

```
sbt:t12554> console
[info] Starting scala interpreter...
Welcome to Scala 2.13.15-20240709-214402-c1fe213 (OpenJDK 64-Bit Server VM, Java 22.0.1).
Type in expressions for evaluation. Or try :help.

scala> 42
val res0: Int = 42
```

I think I had a problem at some point this year and remembered Seth saying it was broken, alas, but I don't remember the context.

This allows me to fib about the version and possibly consume dependencies without building them.
```
scalaVersion := "2.13.14"
```
