### ISSUE TITLE
Community build failures

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5808]
## steps

publish sbt locally
run community build (https://github.com/scala/community-build)

## problem

~~Four~~ Three projects fail to extract: droste, lagom, ~~lift-json~~, playframework
~~Two~~ One project fails to run: ~~gigahorse~~, enumeratum
## expectation

extraction and running succeeds

## notes
~~gigahorse: ~~
~~The version of contraband it is using doesn't work with scala 2.12.12: https://github.com/eed3si9n/gigahorse/pull/74~~
(https://github.com/eed3si9n/gigahorse/pull/74 is merged so gigahorse should work now)

enumeratum:
scala broke binary compatibility in 2.12.11 breaking https://github.com/tkawachi/sbt-doctest
I made a PR to restore binary compatibility for scala: https://github.com/scala/scala/pull/9191
I also made a PR to enumeratum to upgrade sbt-doctest to a version that is unaffected by the broken binary compatibility: https://github.com/lloydmeta/enumeratum/pull/292

droste: 
[droste] [error] These subprojects were not found: "publish".  Found: "root", "docs", "laws", "tests", "reftreeJS", "metaJS", "coverage", "athemaJS", "coreJS", "macrosJS", "lawsJS", "meta", "testsJS", "scalacheck", "macros", "athema", "readme", "core", "reftree", "scalach
eckJS".

~~The extraction can be fixed with a minor adjustment to the droste.conf: https://github.com/scala/community-build/pull/1210~~
The droste project was depending on undefined sbt behavior: https://github.com/higherkindness/droste/pull/180

~~lift-json:~~
~~I added a PR to sbt to sanitize the uri used to construct the bsp id: https://github.com/sbt/sbt/pull/5809~~

lagom:

```
lagom/build.sbt:245: error: value ** is not a member of Seq[xsbti.VirtualFileRef]             
    val products = (a.asInstanceOf[sbt.internal.inc.Analysis]).relations.allProducts.toSeq ** new SimpleFileFilter(                    
                                                                                           ^                                           
[error] sbt.compiler.EvalException: Type error in expression
```

I made a PR to lagom to try and address this: https://github.com/lagom/lagom/pull/3031

playframework:
This project is pinned to  and the following errors are reported:
```
[error] ${BASE}/project/Docs.scala:207:37: overloaded method value create with alternatives:                                            
[error]   (x$1: xsbti.compile.ClassFileManager,x$2: Boolean)xsbti.compile.IncToolOptions <and>                                         
[error]   (x$1: java.util.Optional[xsbti.compile.ClassFileManager],x$2: Boolean)xsbti.compile.IncToolOptions                           
[error]  cannot be applied to (java.util.Optional[Nothing], Boolean)   
[error]     val incToolOpt = IncToolOptions.create(java.util.Optional.empty(), false)                                                   
[error]                                     ^                                                                                          
[error] ${BASE}/project/Docs.scala:210:16: not enough arguments for method run: (sources: List[xsbti.VirtualFile], classpath: List[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: List[String], incToolOptions: xsbti.compile
.IncToolOptions, log: sbt.util.Logger, reporter: xsbti.Reporter)Unit.                                                                   
[error] Unspecified value parameter reporter.                                                                                          
[error]     javadoc.run(sources, classpath, outputDir, options, incToolOpt, streams.log, reporter)                                     
[error]                ^                                                                                                               
[error] ${BASE}/project/Docs.scala:359:73: type mismatch;
[error]  found   : (sources: Seq[xsbti.VirtualFile], classpath: Seq[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: Seq[String], log: sbt.util.Logger, reporter: xsbti.Reporter)Unit <and> (sources: Seq[xsbti.VirtualFile], c
lasspath: Seq[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: Seq[String], maximumErrors: Int, log: sbt.internal.util.ManagedLogger)Unit
[error]  required: sbt.RawCompileLike.Gen
[error]     (which expands to)  (Seq[java.io.File], Seq[java.io.File], java.io.File, Seq[String], Int, sbt.internal.util.ManagedLogger) => Unit                                                
[error]       RawCompileLike.prepare(s"$label Scala API documentation", compile.doc)
[error]                                                                         ^                                                      
[error] ${BASE}/project/Docs.scala:379:45: not enough arguments for method run: (x$1: Array[xsbti.VirtualFile], x$2: Array[String], x$3: xsbti.compile.Output, x$4: xsbti.compile.IncToolOptions, x$5: xsbti.Reporter, x$6: xsbti.Logger)Boolean.
[error] Unspecified value parameter x$6.
[error]             compiler.javaTools().javadoc.run(srcs.toArray, opts.toArray, incToolOptions, reporter, log)
[error]                                             ^
[error] four errors found
```
If I use origin/master instead, I get the following errors:
```
[error] ${BASE}/project/Docs.scala:186:37: overloaded method value create with alternatives:
[error]   (x$1: xsbti.compile.ClassFileManager,x$2: Boolean)xsbti.compile.IncToolOptions <and>
[error]   (x$1: java.util.Optional[xsbti.compile.ClassFileManager],x$2: Boolean)xsbti.compile.IncToolOptions
[error]  cannot be applied to (java.util.Optional[Nothing], Boolean)
[error]     val incToolOpt = IncToolOptions.create(Optional.empty(), false)
[error]                                     ^
[error] ${BASE}/project/Docs.scala:190:16: not enough arguments for method run: (sources: List[xsbti.VirtualFile], classpath: List[xsbti.VirtualFile], converter: xsbti.FileConverter, outputDirectory: java.nio.file.Path, options: List[String], incToolOptions: xsbti.compile.IncToolOptions, log: sbt.util.Logger, reporter: xsbti.Reporter)Unit.
[error] Unspecified value parameter reporter.
[error]     javadoc.run(sources, classpath, outputDir, options, incToolOpt, log, reporter)
[error]                ^
[error] two errors found
```

I made a PR to playframework to fix the type inference issue: https://github.com/playframework/playframework/pull/10442 and a PR to zinc to fix the javadoc binary compatibility issue: https://github.com/sbt/zinc/pull/909

**Comment by eed3si9n** [comment]
I merged this issue into https://github.com/sbt/sbt/issues/5624#issuecomment-688235569
