### ISSUE TITLE
[1.x][2.x] `sbt console` does not work with Scala 2.13.x nightly

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#8294]
### `build.sbt`

```scala
resolvers += Resolver.scalaNightlyRepository

// https://github.com/scala/scala/tree/b656a79771a223b1a8199e39bbc43bd54a13ae0a
scalaVersion := "2.13.17-bin-b656a79"
```

### `project/build.properties`

```properties
sbt.version=1.11.6
```

or

```properties
sbt.version=2.0.0-RC5
```

`sbt console`

## problem

```
[error] java.lang.NoSuchMethodError: 'java.lang.String[] org.jline.terminal.impl.MouseSupport.keys(org.jline.terminal.Terminal)'
[error] 	at org.jline.reader.impl.LineReaderImpl.bindArrowKeys(LineReaderImpl.java:6470)
[error] 	at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:6232)
[error] 	at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:6132)
[error] 	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:351)
[error] 	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:218)
[error] 	at scala.tools.nsc.interpreter.jline.Reader$.apply(Reader.scala:147)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn$lzycompute(ILoop.scala:68)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn(ILoop.scala:63)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:975)
[error] 	at scala.tools.xsbt.ConsoleBridge.run(ConsoleBridge.scala:81)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:208)
[error] 	at sbt.Console.console0$1(Console.scala:65)
[error] 	at sbt.Console.$anonfun$apply$5(Console.scala:75)
[error] 	at sbt.Run$.executeSuccess(Run.scala:178)
[error] 	at sbt.Console.$anonfun$apply$4(Console.scala:75)
[error] 	at sbt.internal.util.Terminal.withRawInput(Terminal.scala:146)
[error] 	at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:144)
[error] 	at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:434)
[error] 	at sbt.Console.$anonfun$apply$3(Console.scala:75)
[error] 	at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:1038)
[error] 	at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:473)
[error] 	at sbt.Console.apply(Console.scala:72)
[error] 	at sbt.Console.apply(Console.scala:50)
[error] 	at sbt.Console.apply(Console.scala:42)
[error] 	at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2353)
[error] 	at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2339)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

## notes

- https://github.com/scala/scala/pull/11125
- sbt 2.0.0-RC5 https://github.com/sbt/sbt/blob/v2.0.0-RC5/project/Dependencies.scala#L82
- sbt 1.11.6 https://github.com/sbt/sbt/blob/v1.11.6/project/Dependencies.scala#L88

**Comment by xuwei-k** [comment]
Should we update jline version in sbt? 🤔

**Comment by xuwei-k** [comment]
note

- https://github.com/sbt/sbt/pull/8018

**Comment by eed3si9n** [comment]
Thanks for finding this.

**Comment by lrytz** [comment]
It seems both `org.jline.reader.impl.LineReaderImpl` and `org.jline.terminal.impl.MouseSupport` are in `jline.jar`.

How can it happen that the two classes are loaded from two different jars? Perhaps one class is loaded from the old jar when running the sbt shell, the other one is loaded from the new jar when running the REPL, something like that?

**Comment by lrytz** [comment]
... were we just lucky so far, or is sbt attempting to isolate the classpath of the Scala REPL and there's a bug in there? If the classes get mixed up between two versions of the same jar, we cannot update sbt's JLine dependency either. New versions of sbt then could fail to run the REPL of old Scala releases.

**Comment by xuwei-k** [comment]
I have encountered similar issue in the past.

- sbt 1.9.7
- Scala 2.13.16

```
Welcome to Scala 2.13.16 (OpenJDK 64-Bit Server VM, Java 21.0.8).
Type in expressions for evaluation. Or try :help.


Failed to initialize compiler: NoSuchMethodError.
This is most often remedied by a full clean and recompile.
Otherwise, your classpath may continue bytecode compiled by
different and incompatible versions of scala.

java.lang.NoSuchMethodError: 'org.jline.utils.AttributedString org.jline.utils.AttributedString.fromAnsi(java.lang.String, java.util.List, java.lang.String, java.lang.String)'
	at org.jline.reader.impl.LineReaderImpl.fromAnsi(LineReaderImpl.java:4236)
	at org.jline.reader.impl.LineReaderImpl.expandPromptPattern(LineReaderImpl.java:4158)
	at org.jline.reader.impl.LineReaderImpl.setPrompt(LineReaderImpl.java:1260)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:628)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:512)
	at scala.tools.nsc.interpreter.jline.Reader.readOneLine(Reader.scala:43)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.jline.Reader.readLine(Reader.scala:33)
	at scala.tools.nsc.interpreter.shell.ILoop.readOneLine(ILoop.scala:453)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:991)
	at scala.tools.xsbt.ConsoleBridge.run(ConsoleBridge.scala:81)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:208)
	at sbt.Console.console0$1(Console.scala:65)
	at sbt.Console.$anonfun$apply$5(Console.scala:75)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Console.$anonfun$apply$4(Console.scala:75)
	at sbt.internal.util.Terminal.withRawInput(Terminal.scala:146)
	at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:144)
	at sbt.internal.util.Terminal$ProxyTerminal$.withRawInput(Terminal.scala:424)
	at sbt.Console.$anonfun$apply$3(Console.scala:75)
	at sbt.internal.util.Terminal$TerminalImpl.withRawOutput(Terminal.scala:1028)
	at sbt.internal.util.Terminal$ProxyTerminal$.withRawOutput(Terminal.scala:463)
	at sbt.Console.apply(Console.scala:72)
	at sbt.Console.apply(Console.scala:50)
	at sbt.Console.apply(Console.scala:42)
	at sbt.Defaults$.$anonfun$consoleTask$1(Defaults.scala:2237)
	at sbt.Defaults$.$anonfun$consoleTask$1$adapted(Defaults.scala:2223)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.Execute.work(Execute.scala:292)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by eed3si9n** [comment]
Various versions of JLine and JAnsi are used by both sbt shell, sbtn, and Scala REPL, and sometimes it's difficult to keep all of them in one JVM process because, if I recall correctly they basically wrap native libraries like DLL files on Windows, and it would break if you have multiple versions of them. At least that used to be the case.

See for example Ethan's commit message from 2020 - https://github.com/sbt/sbt/pull/5711/commits/90dacc339c0bc5afdfa80b98775f235cff56101f. The situation may have changed but it's an interesting record to inform the current design.

> In order to make the console task work with scala 2.13 and the thin
client, we need to provide a way for the scala repl to use an sbt
provided jline3 terminal instead of the default terminal typically built
by the repl. We also need to put jline 3 higher up in the classloading
hierarchy to ensure that two versions of jline 3 are not loaded (which
makes it impossible to share the sbt terminal with the scala terminal).
>
> One impact of this change is the decoupling of the version of
jline-terminal used by the in process scala console and the version
of jline-terminal specified by the scala version itself. It is possible
to override this by setting the `useScalaReplJLine` flag to true. When
that is set, the scala REPL will run in a fully isolated classloader. That
will ensure that the versions are consistent. It will, however, for sure
break the thin client and may interfere with the embedded shell ui.

**Comment by xuwei-k** [comment]
confirmed with `scalaVersion := "2.13.17-bin-0744129"`
