### ISSUE TITLE
Name hashing breaks when using a package object hierarchy

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2326]
- sbt version 0.13.9
- scala version 2.11.7

``` scala
// src/main/scala/p/impl/Foo.scala
package p.impl

trait Foo
```

``` scala
// src/main/scala/p/impl/PackageObject.scala
package p.impl

abstract class PackageObject extends Foo
```

``` scala
// src/main/scala/p/package.scala
import p.impl.PackageObject

package object p extends PackageObject
```

Any change in `Foo.scala`, even adding a space at the beginning of the file, causes:

```
[error] missing or invalid dependency detected while loading class file 'PackageObject.class'.
[error] Could not access type Foo in package p.impl,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'PackageObject.class' was compiled against an incompatible version of p.impl.
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

The current workaround is disabling name hashing:

```
incOptions ~= (_ withNameHashing false)
```

/cc @gkossakowski

[EDIT 2015-12-21: Moved `Foo` and `PackageObject` into a distinct package, and moved files into directories to follow the package structure.. to further remove doubts]

**Comment by paulp** [comment]
Anyone looking at this should look at [SI-9580](https://issues.scala-lang.org/browse/SI-9580) which suggests fundamental breakage in package objects plus inheritance.

**Comment by eed3si9n** [comment]
`Foo` is parent trait of `p`, which `Foo` belongs to? That just sounds immoral.

**Comment by paulp** [comment]
@eed3si9n Pretty sure it's not relevant. In my case one of the first things I did was move everything inherited by the package object into a distinct package. (But yes, the reproduction should be updated to render my speculation unnecessary.)

**Comment by gkossakowski** [comment]
Invalidation of package objects is handled specially by `invalidatedPackageObjects`. At first glance, implementation of that method appears the same to me in both incremental compilation algorithms.
https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/IncrementalDefaultImpl.scala#L13
https://github.com/sbt/sbt/blob/0.13/compile/inc/src/main/scala/sbt/inc/IncrementalNameHashing.scala#L21

That method got introduced in https://github.com/sbt/sbt/commit/cf355f18224332c3311b552cd9a777f5624426a4 to handle the scenario you report. Do you guys see the difference between the test case in that commit and your scenario? The test passes under name hashing.

**Comment by paulp** [comment]
The behavior being reported here can be induced without changing any source code, just by triggering the recompilation of an unchanged file. I think you would do better to start from that observation - how can that be?

**Comment by dwijnand** [comment]
Perhaps because the test case here is a hierarchy 2 deep rather than 1?

**Comment by gkossakowski** [comment]
@dwijnand mentions you need to add a space `Foo.scala` to trigger recompilation. @paulp, is there a way to trigger this issue without any change to `Foo.scala`? How?

**Comment by dwijnand** [comment]
Touching `Foo.scala` doesn't, but removing `target/scala-2.11/classes/p/Foo.class` does. Not sure if that's what Paul meant..

**Comment by paulp** [comment]
Without any change which is supposed to affect compilation products.

**Comment by dwijnand** [comment]
@paulp

> (But yes, the reproduction should be updated to render my speculation unnecessary.)

Missed this edit. Updated the reproduction.

**Comment by dwijnand** [comment]
Shuffling packages changed the error message in a possibly interesting way:

``` diff
- [error] A full rebuild may help if 'PackageObject.class' was compiled against an incompatible version of p.
+ [error] A full rebuild may help if 'PackageObject.class' was compiled against an incompatible version of p.impl.
```

**Comment by dwijnand** [comment]
The following comment by @retronym on SI-4685 might be relevant:

> My vote is to leave this one as is. SBT works around it by deleting package.class when recompiling the package object. One of my roadmap items for 2.12 was to spend a bit of time in package objects (detecting package objects from source before loading the one from the classpath, as Paul has prototyped)

https://issues.scala-lang.org/browse/SI-4695?focusedCommentId=67585&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-67585

**Comment by gkossakowski** [comment]
FYI: I was passing this neighbourhood today and fixed the problem in #2432. Thanks for a minimal reproduction.

**Comment by dwijnand** [comment]
Very cool. Thank you @gkossakowski.

**Comment by gkossakowski** [comment]
Fixed by #2432
