### ISSUE TITLE
NoSuchMethodError: `org.apache.logging.log4j.core.Appender` with sbt 1.4.0

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#5931]
## steps

I wrote a plugin which I am using for quite some time: https://github.com/avdv/sbt-hyperlink

This plugin is published using sbt 1.2.7.

I have this entry in `~/.sbt/1.0/plugins/plugins.sbt`:
```
addSbtPlugin("de.cbley" % "sbt-hyperlink" % "0.1.2")
```

## problem

Now, after upgrading the project sbt version to 1.4.0, and trying to start sbt I see this:
```
java.lang.NoSuchMethodError: 'org.apache.logging.log4j.core.Appender sbt.internal.util.MainAppender$.defaultScreen(sbt.internal.util.ConsoleOut)'
	at sbthyperlink.HyperlinkPlugin$.$anonfun$projectSettings$4(HyperlinkPlugin.scala:94)
	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:127)
	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:70)
	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:185)
	at sbt.std.TaskStreams.log(Streams.scala:72)
	at sbt.std.TaskStreams.log$(Streams.scala:72)
	at sbt.std.Streams$$anon$2$$anon$3.log$lzycompute(Streams.scala:144)
	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:144)
	at sbt.EvaluateTask$.log$1(EvaluateTask.scala:360)
	at sbt.EvaluateTask$.$anonfun$logIncomplete$2(EvaluateTask.scala:364)
	at sbt.EvaluateTask$.$anonfun$logIncomplete$2$adapted(EvaluateTask.scala:359)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at sbt.EvaluateTask$.logIncomplete(EvaluateTask.scala:359)
	at sbt.EvaluateTask$.logIncResult(EvaluateTask.scala:350)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:477)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
	at sbt.EvaluateTask$.$anonfun$apply$3(EvaluateTask.scala:345)
	at scala.Option$WithFilter.map(Option.scala:230)
	at sbt.EvaluateTask$.$anonfun$apply$1(EvaluateTask.scala:344)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.EvaluateTask$.apply(EvaluateTask.scala:343)
	at sbt.EvaluateTask$.evalPluginDef(EvaluateTask.scala:304)
	at sbt.internal.Load$.$anonfun$defaultPreGlobal$1(Load.scala:99)
	at sbt.internal.Load$.buildPluginDefinition(Load.scala:1301)
	at sbt.internal.Load$.buildPlugins(Load.scala:1229)
	at sbt.internal.Load$.plugins(Load.scala:1208)
...
```

## expectation

No exception... :smiley_cat: 

## notes

I am wondering where the log4j.core.Appender dependency is coming from?! Oh, I missed this from the release notes:

> * Replaces Apache Log4j with our own logger by default to avoid Appender leakage. Use ThisBuild / useLog4J := true to use Log4j. #5731 by eatkins

I know that I should probably not use internal APIs, but I don't know how to achieve this without. I am constructing a replacement for the `logManager`:

https://github.com/avdv/sbt-hyperlink/blob/c30cf119c4619475e6a01d8b2fb5ac72b42a6dc3/src/main/scala/sbthyperlink/HyperlinkPlugin.scala#L86-L104

edit: Rebuilding the plugin with sbt 1.4.0 fixed the problem, temporarily.

**Comment by avdv** [comment]
Looking at the changes of #5731 I think that there's no other chance than to release my plugin with 1.4.0 and branch on the `sbtVersion` setting akin to this in my global `plugin.sbt`:
```scala
import sbt.Defaults.sbtPluginExtra

libraryDependencies += {
  val sbtV = (sbtBinaryVersion in pluginCrossBuild).value
  val scalaV = (scalaBinaryVersion in update).value
  val version = if (sbtVersion.value startsWith "1.4") "0.1.2+0-6d092024+20201005-1151" else "0.1.2"
  sbtPluginExtra("de.cbley" % "sbt-hyperlink" % version, sbtV, scalaV)                                                                         
}
```

Other ideas welcome... :wink:

**Comment by avdv** [comment]
Closing, since this is not a bug in sbt, only an (internal) incompatible API change. I have worked around this using reflection: https://github.com/avdv/sbt-hyperlink/pull/9/commits/57e957fda3ddd6eb8ab0dd2b4dd790a8367c66b8
