### ISSUE TITLE
util completion fails to compile

### ISSUE THREAD

**Issue by aolshevskiy** [sbt/sbt#30]
```
[info] == Completion / compile ==
[info]   Source analysis: 9 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[error] /home/siasia/projects/xsbt/util/complete/JLineCompletion.scala:70: value getBuffer is not a member of jline.CursorBuffer
[error]         b.getBuffer.substring(0, b.cursor)
[error]           ^
[error] /home/siasia/projects/xsbt/util/complete/JLineCompletion.scala:105: value printCandidates is not a member of object jline.CandidateListCompletionHandler
[error]         CandidateListCompletionHandler.printCandidates(reader, JavaConversions.asJavaList(cs), true)
[error]                                        ^
[error] two errors found
```

**Comment by aolshevskiy** [comment]
Might be related to http://www.scala-lang.org/node/6802

**Comment by harrah** [comment]
Hmm, interesting.  I can reproduce it on a fresh checkout.  I'll have to git bisect to see when that got messed up, since I don't remember changing anything related recently.  I'd doubt it is related to the linked email, but we'll find out.

**Comment by harrah** [comment]
The cause appears to be the 0.7.7 launcher.  The 0.7.5 launcher works fine for me, does it work for you as well?

**Comment by aolshevskiy** [comment]
Ah, with 0.7.5 everything is fine.
