### ISSUE TITLE
`NoClassDefFoundError` when accessing `javax.sql.DataSource` in console on Java 9+ and Scala 3

### ISSUE THREAD

**Issue by mrdziuban** [sbt/sbt#8664]
## steps

Setup a simple sbt project:
- `project/build.properties` contains `sbt.version=1.12.1`
- `build.sbt` contains `scalaVersion := "3.8.1"`

Load `sbt`, then run `console`. In the console, run:

```scala
classOf[javax.sql.DataSource]
```

## problem

Trying to load `javax.sql.DataSource` results in an error:

```
java.lang.NoClassDefFoundError: javax/sql/DataSource
  ... 62 elided
Caused by: java.lang.ClassNotFoundException: javax.sql.DataSource
  at dotty.tools.repl.AbstractFileClassLoader.findClass$$anonfun$1(AbstractFileClassLoader.scala:55)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
  at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
  at scala.collection.immutable.List.foreach(List.scala:327)
  at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:53)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
  at dotty.tools.io.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:60)
  at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:81)
  ... 62 more
```

## expectation

The class should be loaded successfully as long as the `java.sql` module is available (which it is in my case).

## notes

This works fine in `scala-cli` and `mill`, so I'm guessing it has something to do with sbt's classloader behavior. #4328 may be related, though that's on Scala 2.

**Comment by SethTisue** [comment]
I'd be rather surprised if this doesn't share a root cause with #4328

**Comment by mrdziuban** [comment]
This might only work on Scala 3.8 since the REPL is separate artifact now, but as a workaround I was able to hack together a way to override the `console` task to fork a new `java` process

EDIT: edited to add better `ctrl-c` handling

```scala
import scala.collection.JavaConverters._
import sun.misc.Signal

def consoleTask(conf: Configuration) = Def.task {
  val consoleClasspath = (console / scalaInstance).value.allJars
  val projClasspath = (conf / fullClasspath).value.map(_.data)
  val classpath = (consoleClasspath ++ projClasspath).distinct.mkString(System.getProperty("path.separator"))
  val opts = List("java", "-cp", classpath, "dotty.tools.repl.Main", "-cp", classpath) ++ scalacOptions.value
  val pb = new java.lang.ProcessBuilder(opts.asJava)
  pb.inheritIO()

  // Override ctrl-c signal handling so sbt doesn't exit, only REPL does
  val oldHandler = Signal.handle(new Signal("INT"), _ => ())

  try {
    val proc = pb.start()
    // waitFor might get interrupted by the interruption signal, so loop
    while (proc.isAlive)
      try proc.waitFor()
      catch {
        case _: InterruptedException => // continue waiting
      }
  } finally
    // Restore original ctrl-c signal handler
    Signal.handle(new Signal("INT"), oldHandler)
}

console := consoleTask(Runtime).value
Test / console := consoleTask(Test).value
```

**Comment by Eruis2579** [comment]
Hi, @eed3si9n , Can I try this issue?

**Comment by eed3si9n** [comment]
I'm currently working around the console area (https://github.com/sbt/sbt/issues/8704), so I'd put this issue on hold for a week or two.

**Comment by eed3si9n** [comment]
This is fixed in 2.0.0-RC9 with client-side console.
