### ISSUE TITLE
JARs from global 'lib' are not being added to build dependencies

### ISSUE THREAD

**Issue by 404-** [sbt/sbt#1974]
According to the [Plugins/Global plugins example](http://www.scala-sbt.org/release/docs/Plugins.html#Global+plugins+example) section in the docs:
`Jars may be placed directly in ~/.sbt/0.13/plugins/lib/ and will be available to every build definition for the current user.`
This feature is not working in 0.13.8 (haven't checked any other versions)

Steps:
1. Add `config-1.2.1.jar` (Typesafe config library) JAR under `~/.sbt/0.13/plugins/lib/`
2. In an SBT project, create the following `Build.scala` under the `project` directory:

```
//File: project/Build.scala

import com.typesafe.config.ConfigFactory
import sbt._
import Keys._

object Demo extends Build {}
```

Observed: compilation error while trying to start SBT console:

```
[error] /path/to/demo/project/Build.scala:1: object typesafe is not a member of package com
[error] import com.typesafe.config.ConfigFactory
```
