### ISSUE TITLE
sbt 1.4.6 fails after upgrading scala to 2.12.13

### ISSUE THREAD

**Issue by aaabramov** [sbt/sbt#6251]
## steps

```
sbt clean coverage test coverageReport
```

## problem

sbt 1.4.6 fails after upgrading Scala to 2.12.13 on CI (Jenkins):

```
java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
```

[sbt log and *.sbt files](https://gist.github.com/aaabramov/19b246d055fcf27193731ada98c70f3f)

## expectation

Project compiles successfully

## notes

- **Project relies on plugins source (see attached plugins.sbt)**
- Locally it works completely fine.
- Reverting to 2.12.12 resolves an issue
- Differences between compile logs:
```
# 2.12.13
Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.13. Compiling...

#2.12.12
Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.8. Compiling...
```
- sbt version hasn't been changed

**Comment by aaabramov** [comment]
Similar issue is https://github.com/typelevel/kind-projector/issues/116

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_? For example, does this happen with simple hello world example using sbt new?

**Comment by Christewart** [comment]
Checkout our CI jobs, FWIW i can't reproduce locally. https://github.com/bitcoin-s/bitcoin-s/pull/2509/checks

**Comment by povder** [comment]
The error message suggests that scoverage may be causing this.

**Comment by andrii-abramov-exa** [comment]
@eed3si9n I can't reproduce it locally either. I've reported this issue to coverage https://github.com/scoverage/sbt-scoverage/issues/319

**Comment by aaabramov** [comment]
@eed3si9n I can't reproduce it locally either. I've reported this issue to coverage https://github.com/scoverage/sbt-scoverage/issues/319

**Comment by melezov** [comment]
Hey guys, I don't have anything resembling scoverage and I have the same issue on a number of projects after the 1.4.6 + 2.12.13 bump.

It might be important to mention that I was unable to reproduce on a "fresh" server / docker, what seems to be the combination is reusing of some cached artifacts from previous "2.12.12" compilations.

Edit: I am able to make a reproducible which fails on both local Windows / CentOS by running the same "small" project on 2.12.12 and then bumping the version to 2.12.13. Will try to make a small reproducible with a script.

**Comment by melezov** [comment]
I made a reproducible which consistently fails:
https://github.com/melezov/sbt-reproducibles/tree/master/sbt-1.4.6-feat-scala-2.12.13

If you're unhappy with running a random JAR replace the jar with the 1.4.6 launcher:
https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.4.6/sbt-launch.jar

It spins up a separate user home with /.sbt /.ivy and /.coursier caches to avoid
depending on dirty caches

Tested on AdoptOpenJDK 8/14 and failing both on Windows/CentOS

**Comment by eed3si9n** [comment]
The original issue reported by @aaabramov I think is an sbt-scoverage issue (https://github.com/scoverage/sbt-scoverage/issues/319#issuecomment-761228227), exposed by Scala compiler (rightfully) breaking the bincompat in https://github.com/scala/scala/pull/9300

**Comment by eed3si9n** [comment]
@melezov Thanks Marko for creating a repro project.

Unfortunately, I think the problem you identified is the same theme. In your script you're swapping out the Scala compiler used by sbt mothership with Scala 2.12.13 via launcher configuration.

If you look at the stack trace, I think sbt is trying to parse `build.sbt` file using the Scala compiler, and somewhere when it tries to contact the reporter's `info0` method it's failing. In that sense, sbt also falls into the category of compiler plugin since it uses Scala compiler feature.

<details>
<summary>

```scala
java.lang.AbstractMethodError: scala.tools.nsc.reporters.Reporter.info0(Lscala/reflect/internal/util/Position;Ljava/lang/String;Lscala/reflect/internal/Reporter$Severity;Z)V
	at scala.tools.nsc.reporters.Reporter.nonProtectedInfo0(Reporter.scala:31)
	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
	...
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateStats(Parsers.scala:3163)
	at sbt.internal.parser.SbtParser$.parse(SbtParser.scala:158)
	at sbt.internal.parser.SbtParser.$anonfun$splitExpressions$4(SbtParser.scala:259)
```

</summary>

```scala
java.lang.AbstractMethodError: scala.tools.nsc.reporters.Reporter.info0(Lscala/reflect/internal/util/Position;Ljava/lang/String;Lscala/reflect/internal/Reporter$Severity;Z)V
	at scala.tools.nsc.reporters.Reporter.nonProtectedInfo0(Reporter.scala:31)
	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
	at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:92)
	at scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:116)
	at scala.reflect.internal.Reporter.error(Reporting.scala:111)
	at scala.tools.nsc.Parsing$PerRunParsing.incompleteInputError(Parsing.scala:40)
	at scala.tools.nsc.ast.parser.Parsers$UnitParser.incompleteInputError(Parsers.scala:260)
	at scala.tools.nsc.ast.parser.Parsers$Parser.syntaxErrorOrIncomplete(Parsers.scala:610)
	at scala.tools.nsc.ast.parser.Parsers$Parser.accept(Parsers.scala:630)
	at scala.tools.nsc.ast.parser.Parsers$Parser.blockExpr(Parsers.scala:75)
	at scala.tools.nsc.ast.parser.Parsers$Parser.simpleExpr(Parsers.scala:1716)
	at scala.tools.nsc.ast.parser.Parsers$Parser.prefixExpr(Parsers.scala:1684)
	at scala.tools.nsc.ast.parser.Parsers$Parser.loop$2(Parsers.scala:1655)
	at scala.tools.nsc.ast.parser.Parsers$Parser.postfixExpr(Parsers.scala:1662)
	at scala.tools.nsc.ast.parser.Parsers$Parser.parseOther$1(Parsers.scala:1560)
	at scala.tools.nsc.ast.parser.Parsers$Parser.expr0(Parsers.scala:1614)
	at scala.tools.nsc.ast.parser.Parsers$Parser.$anonfun$expr$1(Parsers.scala:1464)
	at scala.tools.nsc.ast.parser.Parsers$Parser.expr(Parsers.scala:1307)
	at scala.tools.nsc.ast.parser.Parsers$Parser.statement(Parsers.scala:1437)
	at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$templateStat$1.applyOrElse(Parsers.scala:3172)
	at scala.tools.nsc.ast.parser.Parsers$Parser.statSeq(Parsers.scala:3096)
	at scala.tools.nsc.ast.parser.Parsers$Parser.templateStats(Parsers.scala:3163)
	at sbt.internal.parser.SbtParser$.parse(SbtParser.scala:158)
	at sbt.internal.parser.SbtParser.$anonfun$splitExpressions$4(SbtParser.scala:259)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.parser.SbtParser.parseStatementAgain$1(SbtParser.scala:259)
	at sbt.internal.parser.SbtParser.convertStatement$1(SbtParser.scala:276)
	at sbt.internal.parser.SbtParser.$anonfun$splitExpressions$5(SbtParser.scala:280)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at sbt.internal.parser.SbtParser.splitExpressions(SbtParser.scala:280)
	at sbt.internal.parser.SbtParser.<init>(SbtParser.scala:216)
	at sbt.internal.EvaluateConfigurations$.splitExpressions(EvaluateConfigurations.scala:288)
	at sbt.internal.EvaluateConfigurations$.parseConfiguration(EvaluateConfigurations.scala:97)
	at sbt.internal.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:146)
	at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1106)
	at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1116)
	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
	at scala.collection.AbstractMap.getOrElse(Map.scala:65)
	at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1115)
	at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1123)
	at scala.collection.immutable.List.map(List.scala:293)
	at sbt.internal.Load$.loadFiles$1(Load.scala:1123)
	at sbt.internal.Load$.discoverProjects(Load.scala:1137)
	at sbt.internal.Load$.discover$1(Load.scala:889)
	at sbt.internal.Load$.loadTransitive(Load.scala:943)
	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.loadUnit(Load.scala:688)
	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:486)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
	at sbt.internal.Load$.loadURI$1(Load.scala:548)
	at sbt.internal.Load$.loadAll(Load.scala:564)
	at sbt.internal.Load$.loadURI(Load.scala:494)
	at sbt.internal.Load$.load(Load.scala:473)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
	at sbt.internal.Load$.timed(Load.scala:1382)
	at sbt.internal.Load$.apply(Load.scala:242)
	at sbt.internal.Load$.defaultLoad(Load.scala:55)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:932)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:932)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:885)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:242)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:242)
	at sbt.MainLoop$.processCommand(MainLoop.scala:268)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:191)
	at sbt.xMain$.$anonfun$run$8(Main.scala:102)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:557)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:347)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:547)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:547)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:347)
	at sbt.xMain$.run(Main.scala:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.AbstractMethodError: scala.tools.nsc.reporters.Reporter.info0(Lscala/reflect/internal/util/Position;Ljava/lang/String;Lscala/reflect/internal/Reporter$Severity;Z)V
```

</details>
