### ISSUE TITLE
[0.13.7] Cached resolution with ModuleID with `from` clause causes error

### ISSUE THREAD

**Issue by andrewconner** [sbt/sbt#1677]
Unfortunately I haven't minimized the issue(s) yet, but since you guys [encouraged the report](https://twitter.com/scala_sbt/status/522475544131424258), I have a project that's failing to update / compile in sbt 0.13.7-M3 (currently on sbt 0.13.6). If the problem isn't immediately apparent, I'll try to minimize the issue this weekend to have a more descriptive and useful issue.

With  `updateOptions := updateOptions.value.withCachedResolution(true)`, after a clean, during compile, first error (this dependency is used in a sub-project called `cortex`):

```
[error] Unable to parse mini graph: /Users/andrew/.sbt/0.13/dependency/module/static/edu.stanford.nlp.models/stanford-corenlp-models/3.2.0_temp-resolve-1ea9471af1a82ee590b160e2c53d878aba89257b/graphs/graph.json
[info] :: resolving dependencies :: org.scala-sbt.temp#temp-resolve-d2fa6741b7976836894b9b2d8b42286131d87638;1.0
[info]  confs: [compile, runtime, test, provided, optional, compile-internal, runtime-internal, test-internal, plugin, sources, docs, pom, scala-tool]
```

You can find this [graph.json here](http://acon.s3.amazonaws.com/graph.json).

Next, while compiling a different sub-project (called `scraper`):

```
[error] /...path.../ApacheHttpFetcher.scala:25: object HttpHeaders is not a member of package org.apache.http
[error] import org.apache.http.HttpHeaders._
[error]                        ^
[error] /...path.../ApacheHttpFetcher.scala:30: object config is not a member of package org.apache.http.client
[error] import org.apache.http.client.config.RequestConfig
[error]                               ^
[error] /...path.../ApacheHttpFetcher.scala:31: object DeflateDecompressingEntity is not a member of package org.apache.http.client.entity
[error] import org.apache.http.client.entity.{ DeflateDecompressingEntity, GzipDecompressingEntity }
[error]        ^
[error] /...path.../ApacheHttpFetcher.scala:32: object CloseableHttpResponse is not a member of package org.apache.http.client.methods
[error] import org.apache.http.client.methods.{ CloseableHttpResponse, HttpGet }
[error]        ^
... etc ...
```

At the end, the summary of both failures:

```
[trace] Stack trace suppressed: run last cortex/*:update for the full output.
[error] (scraper/compile:compile) Compilation failed
[error] (cortex/*:update) org.json4s.package$MappingException: No usable value for configurations
[error] No usable value for details
[error] No usable value for modules
[error] No usable value for artifacts
[error] No usable value for _1
[error] Parsed JSON values do not match with class constructor
[error] args=
[error] arg types=
[error] constructor=public java.net.URL(java.net.URL,java.lang.String,java.net.URLStreamHandler) throws java.net.MalformedURLException
```

The output of `cortex/*:update`:

```
[kifi-backend] $ cortex/*:update
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.10.0-RC1, 2.10.4, 2.10.2, 2.10.0) -> 2.10.3
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.10.0-RC1, 2.10.4, 2.10.2, 2.10.0) -> 2.10.3
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating {file:/Users/andrew/Documents/workspace/kifi3/kifi-backend/}cortex...
[error] Unable to parse mini graph: /Users/andrew/.sbt/0.13/dependency/module/static/edu.stanford.nlp.models/stanford-corenlp-models/3.2.0_temp-resolve-1ea9471af1a82ee590b160e2c53d878aba89257b/graphs/graph.json
[trace] Stack trace suppressed: run last cortex/*:update for the full output.
[error] (cortex/*:update) org.json4s.package$MappingException: No usable value for configurations
[error] No usable value for details
[error] No usable value for modules
[error] No usable value for artifacts
[error] No usable value for _1
[error] Parsed JSON values do not match with class constructor
[error] args=
[error] arg types=
[error] constructor=public java.net.URL(java.net.URL,java.lang.String,java.net.URLStreamHandler) throws java.net.MalformedURLException
[error] Total time: 0 s, completed Oct 15, 2014 9:59:41 PM
```

Relevant dependency configuration:

```
// for `cortex`'s stanford-nlp dependency:
    "edu.stanford.nlp.models" % "stanford-corenlp-models" % "3.2.0" from
      "http://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/3.2.0/stanford-corenlp-3.2.0-models.jar",
    "edu.stanford.nlp" % "stanford-corenlp" % "3.2.0"

// for `scraper`'s apache http components dependency:
    "org.apache.httpcomponents" % "httpclient" % "4.3.1",
```

This project updates/compiles fine using sbt 0.13.6, and also in sbt 0.13.7-M3 when `withCachedResolution` is not set.

Running Scala 2.10.4. Multi-project with 11 subprojects, most are Play 2.3 apps.

**Comment by eed3si9n** [comment]
Thanks for the report!
