### ISSUE TITLE
sbt-errors-summary does not work with sbt 1.4.8

### ISSUE THREAD

**Issue by note** [sbt/sbt#6379]
## steps

Add sbt-errors-summary to your project (in my case it's a global plugin):

```
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.3")
```

## problem

Sbt project couldn't be loaded. I am getting:

```
welcome to sbt 1.4.8 (AdoptOpenJDK Java 11.0.7)
loading settings for project global-plugins from plugins.sbt ...
loading global plugins from /$HOME/.sbt/1.0/plugins
loading project definition from $PROJECTDIR

java.lang.NoSuchMethodError: 'scala.Function1 sbt.Defaults$.foldMappers(scala.collection.Seq)'
	at sbt.errorssummary.Plugin$.$anonfun$reporterSettings$1(Plugin.scala:39)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

## expectation

I would expect my project to load

## notes

It works just fine if I don't include `sbt-errors-summary`.

I remember there were similar (at least on a surface level) issues with `1.4.0`: https://github.com/sbt/sbt/issues/5935

**Comment by eed3si9n** [comment]
@note Thanks for the report! We did break `foldMappers` method but it's also a `private[sbt]` so 🤷 ?
I suggest you open this issue under sbt-errors-summary.
