### ISSUE TITLE
doc task fails with java.lang.NoClassDefFoundError: scala/xml/NodeSeq

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4995]
_Originally posted by @xuwei-k in https://github.com/scala/scala-xml/pull/348#issuecomment-525703962_

## steps

In scala/scala-xml using sbt 1.3.0-RC4

`sbt ++2.12.9 doc`

## problems

https://travis-ci.org/scala/scala-xml/jobs/577682776#L485

```
model contains 132 documentable templates
[error] java.lang.NoClassDefFoundError: scala/xml/NodeSeq
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.xml.NodeSeq
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (xml / Compile / doc) java.lang.NoClassDefFoundError: scala/xml/NodeSeq
```

`sbt ++2.12.9 doc` fail with sbt 1.3.0-RC4. (success with sbt 1.3.0-RC3)

## expectation

It should work.

## notes by eed3si9n

Also reported as https://github.com/coursier/coursier/issues/1340 to upstream

**Comment by ashawley** [comment]
Strangely, the bug goes away if it rolled back to Scala 2.12.8, see https://github.com/scala/scala-xml/pull/349

**Comment by eatkins** [comment]
I git bisected this and the bug was introduced in 777cc39fcf49a4b8d19214207451d1d02f153ab3.

**Comment by eatkins** [comment]
I also found that doc works with 1.3.0-RC4 with `ThisBuild / useCoursier := false`.

**Comment by eatkins** [comment]
Actually I'm not 100% sure about that commit introducing the issue. Disabling coursier definitely fixes the problem though.

**Comment by eed3si9n** [comment]
Is there a difference in the calculated classpaths?

**Comment by eatkins** [comment]
Not really. I am re-bisecting because I think somehow it wasn't consistently picking up snapshot changes.

**Comment by eatkins** [comment]
Now I'm pretty much certain 777cc39 is the culprit. If I revert it on origin/develop, doc works ok for scala-xml. My guess is that the reason we see the issue here is that it's a cross jvm/js project and somehow the shared source files aren't being seen.

**Comment by eatkins** [comment]
Also, a simpler repro that takes less time is: `sbt xml / doc` (no need to set the cross version).

**Comment by eed3si9n** [comment]
Is it a coincidence that this particular issue of `doc` task not finding `scala/xml/NodeSeq` is happening to scala-xml, or could this potentially happen to other projects?
This reminds me a bit of https://github.com/sbt/sbt/issues/4669 where only on Zinc we couldn't find the compiler bridge because there was one as subproject.

**Comment by eatkins** [comment]
I doubt it's a coincidence because I've never seen doc fail in any other project. That being said, it _does_ work with ivy.

**Comment by eed3si9n** [comment]
Here's `show xml/updateFull` results:

### useCoursier

```
[info] 	scala-tool:
....
[info] 	org.scala-lang.modules:scala-xml_2.12
[info] 		- 1.0.6
[info] 			evicted: true
[info] 			evictedData: version selection
[info] 			extraAttributes: Map(info.apiURL -> https://scala.github.io/scala-xml/api/2.0.0/)
[info] 			configurations: plugin, pom, test, provided, compile-internal, docs, optional, compile, test-internal, scala-tool, sources, runtime, runtime-internal
[info] 			callers: org.scala-lang:scala-compiler:2.12.9
[info]
```

### ThisBuild / useCoursier := false

```
[info] 	scala-tool:
...
[info] 	org.scala-lang.modules:scala-xml_2.12
[info] 		- 1.0.6
[info] 			status: release
[info] 			publicationDate: 2016-11-01T10:21:05-04:00
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			homepage: http://www.scala-lang.org/
[info] 			isDefault: false
[info] 			configurations: compile, runtime(*), master(compile), runtime, compile(*), master
[info] 			licenses: (BSD 3-clause,Some(http://opensource.org/licenses/BSD-3-Clause))
[info] 			callers: org.scala-lang:scala-compiler:2.12.9
```

So with Ivy eviction is localized to a configuration. It appears Coursier is not.

**Comment by eed3si9n** [comment]
I wonder what the effect of this would be on scala/scala.

**Comment by eatkins** [comment]
`publishLocal` and `test` worked for me on the 2.13.x branch using 1.3.0-RC4.

**Comment by Philippus** [comment]
I think we're hitting the same issue in scala-parser-combinators: https://github.com/scala/scala-parser-combinators/pull/237

**Comment by eed3si9n** [comment]
Maybe we can try to fix this by directly invoking LM API to grab the Scala compiler JARs instead of making a weird sandbox configuration.

**Comment by ashawley** [comment]
> Strangely, the bug goes away if it is rolled back to Scala 2.12.8

Circling back on this, I tried the tack of trying to bisect Scala 2.12.9, but I couldn't find a nightly build that doesn't fail.  So the only breaking commit candidate is the first commit of bumping the starr to 2.12.9.  I'm not sure what to conclude from that.

### Steps

Starting scala-xml repo with:

    $ sbt -Dsbt.version=1.3.0
    
    > set resolvers in ThisBuild += "scala-integration" at "https://scalaci.typesafe.com/artifactory/scala-integration/"

Here's the bisect log.  Commits are of the Scala repo, but the comments are the commands to run a nightly from the scala-xml repo.

```
# bad: [cca78e1e18c55e5b0223b9dfa4ac230f7bc6a858] ;++2.12.9;xml/doc
# good: [38cd84d976880eab16af17a44d186bbddcd554f2] ;++2.12.8;xml/doc
git bisect start v2.12.9 v2.12.8
# bad: [8257b839359a72e8072b04584bc00a3d64251f26] ;++2.12.9-bin-8257b83;xml/doc
git bisect bad 8257b839359a72e8072b04584bc00a3d64251f26
# bad: [9862ab7a159673ef232d42c836d85e8fac6f6d54] ;++2.12.9-bin-9862ab7;xml/doc
git bisect bad 9862ab7a159673ef232d42c836d85e8fac6f6d54
# bad: [6f87360ab593067a3e9f33e20f589952c6cb62d7] ;++2.12.9-bin-6f87360;xml/doc
git bisect bad 6f87360ab593067a3e9f33e20f589952c6cb62d7
# skip: [6c8efe908caa4d64f44417f48894202071ed836a] ;++2.12.9-bin-6c8efe9;xml/doc
git bisect skip 6c8efe908caa4d64f44417f48894202071ed836a
# skip: [49a77477658a68f24eb4ab627a1a56c9d2141404] ;++2.12.9-bin-49a7747;xml/doc
git bisect skip 49a77477658a68f24eb4ab627a1a56c9d2141404
# skip: [5125215b8f2e5cd269ed39c38418e8172a3a841f] ;++2.12.9-bin-5125215;xml/doc
git bisect skip 5125215b8f2e5cd269ed39c38418e8172a3a841f
# bad: [329deac9ab4f39e5e766ec3ab3f3f4cddbc44aa1] ;++2.12.9-bin-329deac;xml/doc
git bisect bad 329deac9ab4f39e5e766ec3ab3f3f4cddbc44aa1
# bad: [00c135e0ed022eb228c74aa0bd8f7063495baabe] ;++2.12.9-bin-00c135e;xml/doc
git bisect bad 00c135e0ed022eb228c74aa0bd8f7063495baabe
# bad: [14e043fccdd1166904187f980773c9ae0b7f5dd7] ;++2.12.9-bin-14e043f;xml/doc
git bisect bad 14e043fccdd1166904187f980773c9ae0b7f5dd7
# bad: [7abb8dbcf57e72b374b22550cb2f90708d859bc5] ;++2.12.9-bin-7abb8db;xml/doc
git bisect bad 7abb8dbcf57e72b374b22550cb2f90708d859bc5
# skip: [8b095a954b2f27038ee773b61123a0628646750d] ;++2.12.9-bin-8b095a9;xml/doc
git bisect skip 8b095a954b2f27038ee773b61123a0628646750d
# only skipped commits left to test
# possible first bad commit: [7abb8dbcf57e72b374b22550cb2f90708d859bc5] Merge pull request #7493 from lrytz/bump-2.12.8
# possible first bad commit: [8b095a954b2f27038ee773b61123a0628646750d] Bump starr to 2.12.8
```

**Comment by ashawley** [comment]
Oh, Scala 2.12.10 just got released... no change, unfortunately.

**Comment by nevillelyh** [comment]
I'm hitting a similar issue with scala 2.11.12, sbt 1.3.0, doesn't affect 2.12 or 2.13 though.

Setting `ThisBuild / useCoursier := false` fixes the build.

```
[error] java.lang.NoClassDefFoundError: scala/xml/NamespaceBinding
[error]         at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:124)
[error]         at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:16)
[error]         at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:24)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:121)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:124)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1606)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.xml.NamespaceBinding
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:124)
[error]         at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:16)
[error]         at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:24)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:121)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:124)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1606)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (protobuf-generic / Compile / doc) java.lang.NoClassDefFoundError: scala/xml/NamespaceBinding
```

**Comment by eed3si9n** [comment]
@nevillelyh Thanks for the report.

I kind of thought this was happening only to scala-* projects, but I guess it can affect any project that depends on scala-xml.

**Comment by ashawley** [comment]
@nevillelyh Which version of 2.12?  The doc task works for you with Scala 2.12.9?

**Comment by nevillelyh** [comment]
Yeah works for both 2.12.9 & 2.12.10, which leads to me to suspect that it's not scala but coursier related.

**Comment by alexarchambault** [comment]
@nevillelyh I've been trying to reproduce that with your [protobuf-generic](https://github.com/nevillelyh/protobuf-generic), to no avail:
```
$ pwd
…/protobuf-generic
$ git describe
v0.2.5-4-g9381060
$ vim build.sbt # remove line disabling coursier
$ sbt '+doc' # runs fine
```

edit: nvm, I reproduced and debugged that another way

**Comment by eed3si9n** [comment]
Fixed in https://github.com/coursier/sbt-coursier/pull/136.
`doc` task seems to work on sbt 1.3.2.
