### ISSUE TITLE
Symbol `X` is missing from the classpath

### ISSUE THREAD

**Issue by izhangzhihao** [sbt/sbt#3187]
Use sbt create two project,
the first one named `apackage`
```scala
package missingsymbol {

  package object p  {
    type Container = String
  }

}


package missingsymbol.p {
  class Test extends Container.Nested

  object Container {
    trait Nested
  }
}
```

the second one named `use`

```scala
package use
object use {
  val error = new missingsymbol.p.Test
}
```

scala version is 2.11.11,sbt version is 0.13.15, I got 

```
[error] ScalaIssues#10306/use/src/main/scala/use/use.scala:4: Symbol 'type missingsymbol.p.Container.Nested' is missing from the classpath.
[error] This symbol is required by 'class missingsymbol.p.Test'.
[error] Make sure that type Nested is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Test.class' was compiled against an incompatible version of missingsymbol.p.Container.
[error]   val error = new missingsymbol.p.Test
[error]                   ^
[error] one error found
[error] (use/compile:compileIncremental) Compilation failed
```

But it works fine at scala 2.12.2, also works fine with scalac at scala 2.11.11

The example project in https://github.com/izhangzhihao/ScalaIssues-10306 ,Also see here https://github.com/scala/bug/issues/10306

**Comment by izhangzhihao** [comment]
It's still not fixed in sbt version 1.0.2, see here https://github.com/izhangzhihao/sbt-issue-3187

```
[error] /Downloads/ScalaIssues-10306/use/src/main/scala/use/use.scala:4:19: Symbol 'type missingsymbol.p.Container.Nested' is missing from the classpath.
[error] This symbol is required by 'class missingsymbol.p.Test'.
[error] Make sure that type Nested is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Test.class' was compiled against an incompatible version of missingsymbol.p.Container.
[error]   val error = new missingsymbol.p.Test
[error]                   ^
[error] one error found
[error] (use/compile:compileIncremental) Compilation failed
```

**Comment by godenji** [comment]
Seeing the same in 1.0.2, can workaround by switching to affected subproject and doing a `;clean;compile`. Would be great if this issue gets resolved in next release.

**Comment by ArturGajowy** [comment]
Had the same issue today on teamcity, can't reproduce locally or on a different teamcity agent...

**Comment by suriyanto** [comment]
I'm encountering the same issue when trying to use the class from other subproject inside the test for the current subproject. The `;clean;compile` workaround does not seem to help in this case.

**Comment by aroraakshit** [comment]
Same issue. ;clean;compile doesn't work!

**Comment by isaias-b** [comment]
I had this issue using sbt `1.1.4`. `clean` and `compile` didn't help as well. But in my case i was able to figure out the problem, or at least resolve it differently:
```
[error] ... PATH:LINE: Symbol 'type akka.stream.scaladsl.Flow' is missing from the classpath.
[error] This symbol is required by 'value akka.http.scaladsl.HttpExt.handler'.
[error] Make sure that type Flow is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'HttpExt.class' was compiled against an incompatible version of akka.stream.scaladsl.
[error]     val futureBinding = Http().bindAndHandle(
[error]                             ^
```
This bug occurred after bumping several dependencies on one of my projects. After investigating the [akka http changelogs for version `10.1.0` and `10.1.x`](https://akka.io/blog/news/2018/03/08/akka-http-10.1.0-released) I got this hint out of the documentation:
> Using Akka HTTP with Akka 2.5 used to be a bit confusing, because Akka HTTP explicitly depended on Akka 2.4. Trying to use it together with Akka 2.5, running an Akka HTTP application could fail with class loading issues if you forgot to add a dependency to both akka-actor and akka-stream of the same version. For that reason, we changed the policy not to depend on akka-stream explicitly anymore but mark it as a provided dependency in our build. That means that you will always have to add a manual dependency to akka-stream (veterans may remember this policy from Spray).

So i just added the `akka-stream` dependency which is currently commented out:
```
    val akkaVersion = "2.5.12"
    val akkaHttpVersion = "10.1.1"
    Def.setting(
      Seq(
//        "com.typesafe.akka" %% "akka-stream" % akkaVersion,
        "com.typesafe.akka" %% "akka-slf4j" % akkaVersion,
        "com.typesafe.akka" %% "akka-http" % akkaHttpVersion,
        "com.typesafe.akka" %% "akka-http-testkit" % akkaHttpVersion % Test,
```

And now that silly error disappeared 🎊

**Comment by mlangc** [comment]
This bug is still there with SBT-1.3.8 & Scala-2.11.12 (see https://github.com/mlangc/sbt-issue-3187 to reproduce it).

**Comment by baaa** [comment]
This in fact still is there in 1.3.8 3 years and counting compiling projects individually...

**Comment by crakjie** [comment]
Still existing in 1.4.1. This issue is annoying for CI stages make use of clean
 mandatory, increasing the overall staging durations.

**Comment by eed3si9n** [comment]
In https://github.com/scala/bug/issues/10306#issuecomment-300545310 @dwijnand wrote
> I can't reproduce it with scalac. But I can reproduce it with sbt 0.13.15 and sbt 1.0.0-M5.

I'm not sure what Dale did there, but this looks like Scala compiler failing to extract the correct pickle from the class file or something, so we need to compile these individually.

## steps for Scala 2.11.11

```bash
$ wget https://downloads.lightbend.com/scala/2.11.11/scala-2.11.11.tgz
$ tar xf scala-2.11.11.tgz
$ ls scala-2.11.11/bin/scalac
scala-2.11.11/bin/scalac*
$ mkdir -p apackage/target/scala-2.11/classes/
$ ./scala-2.11.11/bin/scalac apackage/src/main/scala/com/github/izhangzhihao/package.scala -d apackage/target/scala-2.11/classes/
$ ls apackage/target/scala-2.11/classes/**/*.class
apackage/target/scala-2.11/classes/missingsymbol/p/Container$.class        apackage/target/scala-2.11/classes/missingsymbol/p/Container.class         apackage/target/scala-2.11/classes/missingsymbol/p/package$.class
apackage/target/scala-2.11/classes/missingsymbol/p/Container$Nested.class  apackage/target/scala-2.11/classes/missingsymbol/p/Test.class              apackage/target/scala-2.11/classes/missingsymbol/p/package.class

$ mkdir -p use/target/scala-2.11/classes/
$ ./scala-2.11.11/bin/scalac use/src/main/scala/use/use.scala -cp apackage/target/scala-2.11/classes/ -d use/target/scala-2.11/classes/
use/src/main/scala/use/use.scala:4: error: Symbol 'type missingsymbol.p.Container.Nested' is missing from the classpath.
This symbol is required by 'class missingsymbol.p.Test'.
Make sure that type Nested is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'Test.class' was compiled against an incompatible version of missingsymbol.p.Container.
  val error = new missingsymbol.p.Test
                  ^
one error found
```

Even without this, the fact that Zhihao Zhang reported on the same day that it works on Scala 2.12.2 makes me strongly suspicious this is a Scala 2.11 bug, not sbt.

## works fine on Scala 2.12 and 2.13

```
$ sbt
[info] welcome to sbt 1.4.2 (AdoptOpenJDK Java 1.8.0_232)
[info] loading settings for project global-plugins from idea.sbt,pgp.sbt,plugins.sbt,vimquit.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] loading project definition from /private/tmp/sbt-issue-3187/project
[info] loading settings for project sbt-issue-3187 from build.sbt ...
[info] set current project to sbt-10306 (in build file:/private/tmp/sbt-issue-3187/)
[info] sbt server started at local:///Users/eed3si9n/.sbt/1.0/server/c34d0b5fa903a215edb6/sock
sbt:sbt-10306> scalaVersion
[info] apackage / scalaVersion
[info] 	2.11.11
[info] use / scalaVersion
[info] 	2.11.11
[info] scalaVersion
[info] 	2.11.11
sbt:sbt-10306> compile
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/apackage/target/scala-2.11/classes ...
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/use/target/scala-2.11/classes ...
[error] /private/tmp/sbt-issue-3187/use/src/main/scala/use/use.scala:4:19: Symbol 'type missingsymbol.p.Container.Nested' is missing from the classpath.
[error] This symbol is required by 'class missingsymbol.p.Test'.
[error] Make sure that type Nested is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Test.class' was compiled against an incompatible version of missingsymbol.p.Container.
[error]   val error = new missingsymbol.p.Test
[error]                   ^
[error] one error found
[error] (use / Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Nov 15, 2020 5:06:47 PM
sbt:sbt-10306> ++2.12.12!
[info] Forcing Scala version to 2.12.12 on all projects.
[info] Reapplying settings...
[info] set current project to sbt-10306 (in build file:/private/tmp/sbt-issue-3187/)
sbt:sbt-10306> compile
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/apackage/target/scala-2.12/classes ...
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/use/target/scala-2.12/classes ...
[success] Total time: 3 s, completed Nov 15, 2020 5:07:04 PM
sbt:sbt-10306> ++2.13.3!
[info] Forcing Scala version to 2.13.3 on all projects.
[info] Reapplying settings...
[info] set current project to sbt-10306 (in build file:/private/tmp/sbt-issue-3187/)
sbt:sbt-10306> compile
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/apackage/target/scala-2.13/classes ...
[info] compiling 1 Scala source to /private/tmp/sbt-issue-3187/use/target/scala-2.13/classes ...
[success] Total time: 3 s, completed Nov 15, 2020 5:07:15 PM
```

All in all I'd conclude this to be not-a-🐛.

**Comment by hartmut27** [comment]
as a work-around using ```Scala 2.13.4``` with SBT & bloop/BSP I do a ```rm -rf .bloop/{myprojectname}``` each time, then ```Symbol X is missing from the classpath``` disappears. In the most cases  this problem occurs, when I do refactorings, say: moving source code fragments from one to another class in a different folder. (It happens even more often, when the package object at root level of an package folder is involved)
