### ISSUE TITLE
NoClassDefFoundError when generating test reports with ScalaTest

### ISSUE THREAD

**Issue by gavinbaumanis** [sbt/sbt#5308]
Ref https://github.com/sbt/sbt/pull/5273

## steps
Mac OSX Catalina
sbt binary version: (brew install sbt) : 1.3.4
Version defined in build.properties : 1.3.5

#### build.sbt

```scala
import Dependencies._

ThisBuild / scalaVersion     := "2.13.1"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-5308",
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.0" % Test,
    libraryDependencies += "com.vladsch.flexmark" % "flexmark-all" % "0.35.10" % Test,
    Test / testOptions += Tests.Argument(TestFrameworks.ScalaTest, "-h", "target/generated/test-reports"),
  )
```

Then

```
test
```

## problem
sbt test fails with the following stack trace;

```
[info] Compiling 25 Scala sources to /Users/gavinbaumanis/workspace/ecpr/pas/target/scala-2.13/test-classes ...
[error] java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
[error] 	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
[error] 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
[error] 	at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:120)
[error] 	at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:38)
[error] 	at scala.collection.immutable.List$.from(List.scala:617)
[error] 	at scala.collection.immutable.List$.from(List.scala:611)
[error] 	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:44)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:41)
[error] 	at scala.collection.IterableOps.map(Iterable.scala:672)
[error] 	at scala.collection.IterableOps.map$(Iterable.scala:672)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:670)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1124)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1096)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:159)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1090)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1158)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:895)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
    )
[error] Caused by: java.lang.ClassNotFoundException: com.vladsch.flexmark.ast.Node
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
[error] 	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
[error] 	at scala.collection.Iterator$$anon$9.next(Iterator.scala:573)
[error] 	at scala.collection.mutable.ListBuffer.addAll(ListBuffer.scala:120)
[error] 	at scala.collection.mutable.ListBuffer$.from(ListBuffer.scala:38)
[error] 	at scala.collection.immutable.List$.from(List.scala:617)
[error] 	at scala.collection.immutable.List$.from(List.scala:611)
[error] 	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:44)
[error] 	at scala.collection.immutable.Seq$.from(Seq.scala:41)
[error] 	at scala.collection.IterableOps.map(Iterable.scala:672)
[error] 	at scala.collection.IterableOps.map$(Iterable.scala:672)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:253)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:670)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1124)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1096)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:159)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1090)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1158)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:895)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Test / executeTests) java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
[error] Total time: 11 s, completed 14 Dec. 2019, 9:43:57 am

```

## expectation
sbt test to complete successfully

## notes
sbt binary 1.3.4 AND build.properties 1.3.4 does NOT have this issue.

**Comment by eed3si9n** [comment]
@gavinbaumanis Thanks for the report. I can reproduce this using sbt 1.3.4.

```scala
import Dependencies._

ThisBuild / scalaVersion     := "2.13.1"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-5308",
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.0" % Test,
    Test / testOptions += Tests.Argument(TestFrameworks.ScalaTest, "-h", "target/generated/test-reports")
  )
```

POM for ScalaTest says flexmark-all is optional http://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.1.0/scalatest_2.12-3.1.0.pom

```xml
<dependency>
  <groupId>com.vladsch.flexmark</groupId>
  <artifactId>flexmark-all</artifactId>
  <version>0.35.10</version>
  <optional>true</optional>
</dependency>
```

Coursier is probably not including this into the resolution.

```
sbt:sbt-5308> show Test/externalDependencyClasspath
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/1.2.0/scala-xml_2.13-1.2.0.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.1.0/scalatest-compatible-3.1.0.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalactic/scalactic_2.13/3.1.0/scalactic_2.13-3.1.0.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.1/scala-reflect-2.13.1.jar)
[info] * Attributed(/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.1.0/scalatest_2.13-3.1.0.jar)
```

**Comment by eed3si9n** [comment]
Using the following build

```scala
import Dependencies._

ThisBuild / scalaVersion     := "2.13.1"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-5308",
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.0" % Test,
    libraryDependencies += "com.vladsch.flexmark" % "flexmark-all" % "0.35.10" % Test,
    Test / testOptions += Tests.Argument(TestFrameworks.ScalaTest, "-h", "target/generated/test-reports"),
  )
```

it works with sbt 1.3.4, but it doesn't work on sbt 1.3.5.

**Comment by eed3si9n** [comment]
@eatkins I wonder if this is related to the new ScalaTest stuff since it won't include flexmark-all in it. Is this because of the layer ordering?

**Comment by gavinbaumanis** [comment]
I didn't think to add the relevant build lines - sorry and thanks.
I have the flexmark-all dependency at 0.35.10 in my build, too.
It is certainly required if generating the test reports.

(I think) Previous versions of ScalaTest used Pegdown which is now abandoned.

**Comment by plokhotnyuk** [comment]
Got the same exception on test report generation for ScalaTest 3.0.8: https://github.com/plokhotnyuk/jsoniter-scala/pull/442

**Comment by mwz** [comment]
I'm also seeing the `NoClassDefFoundError` exception when executing scalatest (`3.0.8`) with sbt `1.3.5` in my project - works perfectly fine with `1.3.4`.

Here is the PR https://github.com/mwz/sonar-scala/pull/314.

> [error] java.lang.NoClassDefFoundError: org/scalacheck/Test$TestCallback

Here is the full trace:
```
[error] java.lang.NoClassDefFoundError: org/scalacheck/Test$TestCallback
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.loadSuiteClass(Framework.scala:402)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.suiteClass$lzycompute(Framework.scala:410)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.suiteClass(Framework.scala:410)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.accessible$lzycompute(Framework.scala:411)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.accessible(Framework.scala:411)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.shouldDiscover$lzycompute(Framework.scala:414)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.shouldDiscover(Framework.scala:414)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.$anonfun$tasks$2(Framework.scala:731)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.$anonfun$tasks$2$adapted(Framework.scala:729)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:827)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:826)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.tasks(Framework.scala:729)
[error] 	at sbt.TestRunner.tasks(TestFramework.scala:107)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$4(TestFramework.scala:263)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$3(TestFramework.scala:263)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$3$adapted(TestFramework.scala:260)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error] 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:256)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:256)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at sbt.TestFramework$.createTestTasks(TestFramework.scala:260)
[error] 	at sbt.TestFramework$.testTasks(TestFramework.scala:218)
[error] 	at sbt.Tests$.testTask(Tests.scala:237)
[error] 	at sbt.Tests$.apply(Tests.scala:216)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$1(Defaults.scala:1179)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1159)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:895)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

You can find the full log output here https://circleci.com/gh/mwz/sonar-scala/1098.

**Comment by eed3si9n** [comment]
I am not sure if this is related but there was an error that was caught running Community Build - https://github.com/scala/community-build/pull/1018#issuecomment-565691765

```
[twirl] [info] Twirl compiler
[twirl] [info] - should compile successfully (real) *** FAILED ***
[twirl] [info]   play.twirl.compiler.test.Helper$CompilationError: Symbol 'type scala.xml.NodeSeq' is missing from the classpath.
[twirl] [info] This symbol is required by 'value play.twirl.api.BaseScalaTemplate.x'.
[twirl] [info] Make sure that type NodeSeq is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[twirl] [info] A full rebuild may help if 'BaseScalaTemplate.class' was compiled against an incompatible version of scala.xml.
[twirl] [info] (NOTE: It looks like the scala-xml module is missing; try adding a dependency on "org.scala-lang.modules" : "scala-xml".
[twirl] [info]        See http://docs.scala-lang.org/overviews/ for more information.)
```

https://github.com/playframework/twirl/blob/df09ed602a5cb232f9eee2c2af53227da57101d7/compiler/src/test/scala/play/twirl/compiler/test/CompilerSpec.scala looks like a ScalaTest test. I am unsure if this is the same issue because scala-xml I thought was specifically included into the new ClassLoader.

**Comment by ritschwumm** [comment]
another one i guess is related, this one happens in most of my projects when running `sbt test` with specs2:
```
Exception in thread "specs2-8" java.lang.NoClassDefFoundError: scala/reflect/api/Trees$TreeApi
	at org.specs2.io.DirectoryPath$.unsafe(DirectoryPath.scala:111)
	at org.specs2.io.FilePath$.unsafe(DirectoryPath.scala:176)
	at org.specs2.io.DirectoryStore.filepath(DirectoryStore.scala:22)
	at org.specs2.io.DirectoryStore.set(DirectoryStore.scala:11)
	at org.specs2.specification.process.StatisticsRepository.storeResult(StatisticsRepository.scala:30)
	at org.specs2.reporter.Reporter.$anonfun$statsStoreSink$2(Reporter.scala:64)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:386)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:198)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:386)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:198)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:198)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:386)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.Interpret.$anonfun$interpretLoop$11(Interpret.scala:198)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.CollectedUnions.$anonfun$othersEff$1(Unions.scala:97)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:386)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.IntoPolyLower4$$anon$15.$anonfun$apply$62(IntoPoly.scala:220)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.IntoPolyLower4$$anon$15.$anonfun$apply$62(IntoPoly.scala:220)
	at org.specs2.control.eff.Arrs.go$1(Eff.scala:383)
	at org.specs2.control.eff.Arrs.apply(Eff.scala:399)
	at org.specs2.control.eff.EffInterpretation.$anonfun$detachA$8(Eff.scala:316)
	at org.specs2.fp.Monad.$anonfun$map$2(Monad.scala:22)
	at org.specs2.control.eff.TimedFuture$$anon$2.$anonfun$point$2(FutureEffect.scala:57)
	at org.specs2.control.eff.TimedFuture.$anonfun$runNow$1(FutureEffect.scala:15)
	at scala.Option.fold(Option.scala:263)
	at org.specs2.control.eff.TimedFuture.runNow(FutureEffect.scala:16)
	at org.specs2.control.eff.TimedFuture$$anon$2.$anonfun$bind$2(FutureEffect.scala:60)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.reflect.api.Trees$TreeApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
```

**Comment by felixbr** [comment]
I have a similar issue in 1.3.5 (works fine in 1.3.4) where `org/mockito/Mockito` cannot be found during the test-run.

We're using Scalatest with its `MockitoSugar` if that is any help.

**Comment by ennru** [comment]
> I have a similar issue in 1.3.5 (works fine in 1.3.4) where org/mockito/Mockito cannot be found during the test-run.

> We're using Scalatest with its MockitoSugar if that is any help.

Same in Alpakka https://github.com/akka/alpakka/pull/2056: all subprojects using Mockito fail in `test` with 1.3.5 eg https://travis-ci.com/akka/alpakka/jobs/269006934#L496
It works with sbt 1.3.4 and with 1.3.5 if I add `Test/fork:=true`.

**Comment by ennru** [comment]
Oh, I apologize: I didn't see the great hint from sbt https://travis-ci.com/akka/alpakka/jobs/269006934#L687 until now.

**Comment by dwijnand** [comment]
Fixed with the revert in #5327.

**Comment by liebichw** [comment]
This problem is still occuring with sbt 1.3.8.

**Comment by SethTisue** [comment]
@liebichw how would we reproduce the problem on our own computers?

**Comment by kiemlicz** [comment]
1.3.13 also affected, although works in 1.3.12

https://github.com/kiemlicz/shelm/blob/master/build.sbt

adding (`build.sbt`), plus utilizing any class from added library:
```
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-yaml" % "0.13.1",
      "org.apache.commons" % "commons-compress" % "1.20",     // <-----
    ),
```
yields aforementioned errors

Fun fact: 
1. publishLocal with 1.3.13 - aforementioned error
2. publishLocal with 1.3.12 - works
3. publishLocal with 1.3.13 - works now

Dunno what the issue is or what kind of cache magic is that

**Comment by blakehawkins** [comment]
I have this stacktrace also in sbt 1.4.x and 1.7.1 - scalatest 3.1.2

**Comment by SethTisue** [comment]
do we have any reason to believe the root cause is in sbt, rather than the root cause being in ScalaTest?

ScalaTest 3.1.2 is an old version; have you tried using the latest?

**Comment by blakehawkins** [comment]
> do we have any reason to believe the root cause is in sbt, rather than the root cause being in ScalaTest?

Here is the equivalent scalatest issue: https://github.com/scalatest/scalatest/issues/1736

I think this issue is opened in sbt because it is strange that downgrading sbt only can resolve the issue. Random uninformed hypothesis: a change in SBT dep resolution (Coursier) exposes this issue.

> ScalaTest 3.1.2 is an old version; have you tried using the latest?

Scalatest 3.1.x is the latest version supported by scalajs 0.6.x. Both of these are old versions and I would love to upgrade them, but unfortunately I need to incrementally upgrade individual components to suss out other breaks.

Unfortunately, pinning flexmark on either 0.35.10 or 0.36.8 or 0.62.2 in libraryDependencies doesn't resolve the issue for me
