### ISSUE TITLE
Sbt can't build with Scala 2.11

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1523]
The workaround implemented in #1509 breaks sbt build with Scala 2.11. The failure is:

```
[error] /localhome/jenkinsdbuild3/workspace/Community-2.11.x/target-0.9.1/project-builds/sbt-85b2a717c4973e098c7eb55d9d90dcbd2011dbb2/main/actions/src/main/scala/sbt/compiler/Eval.scala:355: overriding method error in class CompilationUnit of type (pos: Eval.this.global.Position, msg: String)Unit;
[error]  method error cannot override final member
[error]     override def error(pos0: Position, msg: String) = {
[error]                  ^
[error] one error found
[error] (actions/compile:compile) Compilation failed
```

The work-around is being broken by scala/scala#3820 and scala/scala#3868.

We could make the `CompilationUnit.errror` method non-final but that would just obfuscate the fact that the work-around from #1509 is not working anymore. Compiler internals do not call `CompilationUnit.error` anymore so overriding that method doesn't let you intercept reported errors (and their positions).

**Comment by gkossakowski** [comment]
Some quality time spent with debugger resulted in https://issues.scala-lang.org/browse/SI-8794

We'll be able to replace workaround from #1509 with proper fix that propagates current unit to all necessary places.
