### ISSUE TITLE
[1.3.0-RC5] Regression with dependency order

### ISSUE THREAD

**Issue by cquiroz** [sbt/sbt#5024]
## steps
sbt version: 1.3.0-RC5

## problem
A working project using sbt 1.2.8 fails to compile with 1.3.0-RC5. A reduction of the project scope seems to indicate that there is a problem with the order of dependencies. 

In particular the project depends on squants 1.4.0 but a dependency depends on squants 0.6.3. A method on the new squants version `.toMillimetersOfMercury` is called and is available after 0.6.3

With sbt 1.2.8 the code compiles fine but with 1.3.0-RC5 it fails to find the method indicating that is using the older version
```
[error] /Users/cquiroz/Projects/sbtsample/src/main/scala/demo.scala:6:15: value toMillimetersOfMercury is not a member of squants.motion.Pressure
[error]     println(p.toMillimetersOfMercury)
```

A minimal reproduction is available at
https://github.com/cquiroz/sbt-1.3.0-RC5-failure

## expectation
sbt 1.3.0-RC4 Should pick up the correct dependency version

## notes
Note that squants changed organization so one doesn't evict the other. We have
`com.squants:squants_2.12:0.6.3` and `org.typelevel:squants_2.12:1.4.0`

I think the order of the dependencies changed making it pick the first over the second unlike with sbt 1.2.8

**Comment by eed3si9n** [comment]
@cquiroz Thanks for the report. In sbt 1.3.0 we changed the dependency resolver to use Coursier, so some changes in the resolution ordering is expected.

In general, I don't think you should rely on the implementation detail of what JAR ordering Ivy or sbt is sorting the files. Maybe you could request squants project to change the package name if they changed the organization name?
