### ISSUE TITLE
Fold in sbt-dependency-graph (or its core features)

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#5244]
I believe sbt-dependency-graph to be a major plugin in the ecosystem (it's my longest living global plugin) and I believe its functionality, or at least its core features - commands/tasks, should be part of sbt proper.

**Comment by eed3si9n** [comment]
I wanted to do this in Athens too.

**Comment by eatkins** [comment]
The one issue I have with this is that it adds a _lot_ of settings to the build. In akka, adding the plugin increases the number of settings by roughly 10k. I agree that the functionality should ideally be built in though.

**Comment by ceedubs** [comment]
I've been struggling with this since sbt started using Coursier. Is there _any_ way to see a dependency tree for an SBT 1.3.x project? If I try adding `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC3-3")` just to get the `coursierDependencyTree` command, it fails with `java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;`. And `sbt-dependency-graph` [isn't an option](https://github.com/jrudolph/sbt-dependency-graph/issues/178) either.

**Comment by SethTisue** [comment]
@ceedubs have you tried sbt-dependency-graph v0.10.0-RC1? according to the discussion on the ticket you linked to, it works with 1.3 — except perhaps not 100% works, but works for at least some people.

**Comment by ceedubs** [comment]
@SethTisue thanks for pointing me in that direction. I just tried it out and it seems to be working for me. I had tried a previous version that failed and then read the readme/issue about it not working for SBT 1.3 and assumed that was still the case. This is great news.

**Comment by eed3si9n** [comment]
This was done in https://github.com/sbt/sbt/pull/5880
