### ISSUE TITLE
1.1.0-RC1 breaks sbt-release 

### ISSUE THREAD

**Issue by jozic** [sbt/sbt#3792]
This is mostly FYI, as sbt-release should probably not depend on internal
## steps

start `release`

## problem
```
sbt:scalax-collection> release
[info] Starting release process off commit: f58dfd76d214fd2becda20dd67786a0eaf7a5733
[info] Checking remote [origin] ...
[info] Setting scala version to 2.11.12
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
[error] 	at sbtrelease.Load$.structureIndex(Load.scala:58)
[error] 	at sbtrelease.Load$.reapply(Load.scala:20)
[error] 	at sbtrelease.ReleaseStateTransformations$.switchScalaVersion(ReleaseExtra.scala:309)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$2(ReleaseExtra.scala:319)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$1(ReleaseExtra.scala:318)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$6(ReleasePlugin.scala:189)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:194)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
```

## expectation

release works

## notes

sbt version: 1.1.0-RC1
sbt-release version: 1.0.6 

release still works with sbt 1.0.3, didn't check 1.0.4

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-release/pull/215

**Comment by eed3si9n** [comment]
@jozic Thanks for the report.

@xuwei-k Thanks for fixing sbt-release.

Now that it's addressed on the plugin side, I'm going to close this for now.
