### ISSUE TITLE
`clean` is needed while upgrading from sbt-0.13.1 to sbt-0.13.2

### ISSUE THREAD

**Issue by vn971** [sbt/sbt#1323]
Steps how I can reproduce the issue:
- start SBT version 0.13.1 on my project, do `clean`, then `compile`. It will succeed
- stop SBT
- change version to 0.13.2
- start SBT, do `compile`. At this moment a compilation error appears. 

Notes that can be useful:
- scalaVersion of the project is 2.10.3
- during the second (last) `compile`, SBT recompiles all the classes present. At least it writes the same number. `"Compiling 234 Scala sources to"`
- the project uses Twirl plugin. I removed all other plugins but Twirl can't be removed because some of the code depend on it.
- twirl didn't render its html-s to scala, as it usually does after `clean`.
- The compilation error is not directly related to Twirl (if related at all). At least the error itself is about classes outside of twirl:

```
[error] /*****.scala:255: type mismatch;
[error]  found   : ***.A
[error]  required: ***.B
[error]         data.accounts.add(user.id, someAccount)
[error]                                    ^
```

Where A is an obvious subtype of B. The B is a trait and A is a `case class A(***) extends B { override some val-s here}`

**Comment by eed3si9n** [comment]
What is your expected outcome? A better documentation on our part or automatic detection of sbt upgrade and cleaning?

**Comment by vn971** [comment]
Well, it's not an issue for me personally because I already know how to avoid that (to `clean`). But I wrote about this behavior on the mailing list and Josh Suereth said that it could be useful to open a ticket ("Please open a ticket if you can grab more information").

If that's not the case or it's no longer useful then I can close the issue. It was more for SBT developers than for me anyway.

The ML topic was "[sbt-dev] [ANNOUNCE] sbt 0.13.5-RC2 is released".

As for me personally, I'd prefer an automatic clean-up, or just nothing.

**Comment by eed3si9n** [comment]
Got it. Thanks for the clarification.

**Comment by jsuereth** [comment]
Question, did you see this issue from 0.13.1->0.13.5? I think this may be resolved.

**Comment by vn971** [comment]
@jsuereth  Same behavior, SBT showed a compilation error after upgrading to 0.13.5.  Steps to reproduce are the same as in this issue (but with 0.13.5).

**Comment by vn971** [comment]
Closing the ticket because it's too old (sbt-0.13.2 at May 2014).
