### ISSUE TITLE
Regression in SBT 0.13.9 incremental compilation

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#2229]
I've been working with versions of SBT 0.13.x where x < 9, and when switching branches, I've never had a problem when reloading, except for real problems in my code.  

With SBT 0.13.9, I've made very simple modifications in my `build.sbt` file like the following:

Before:

``` scala
val myTask = taskKey[Unit]("My task")
myTask := {
   taskA.value
   taskC.value
}
```

After:

``` scala
val myTask = taskKey[Unit]("My task")
myTask := {
   taskA.value
   taskB.value
   taskC.value
}
```

Reported problem after `reload` or rebooting SBT:

```
error: value value is not a member of sbt.SettingKey
```

The workaround is to do simply a `rm -rf project/target` and reload.

NOTE: if you ask me to find the simplest `build.sbt` that reproduces the error, my answer is that this process is too tedious and time-consuming for me to do.

**Comment by DavidPerezIngeniero** [comment]
I've defined this command to avoid this problem:

``` scala
commands += Command.command("fullReload") { est ⇒
    IO.delete(Project.extract(est).get(baseDirectory) / "project/target")
    est.copy(remainingCommands = "reload" +: est.remainingCommands)
}
```

**Comment by DavidPerezIngeniero** [comment]
I can provide my `build.sbt` if necessary.

**Comment by eed3si9n** [comment]
Between the branch switching does the sbt version change?

**Comment by DavidPerezIngeniero** [comment]
No, I've checked that previous version of SBT also exhibits this problem.
Probably, this problem has arised as my `build.sbt` has become more complex.

In related issue #2203, I've explained some conclusions.

**Comment by metasim** [comment]
FWIW: I also have this problem in 0.13.16
Happened after I changed some code in a subproject `build.sbt` and ran a fresh sbt instance.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know.

**Comment by DavidPerezIngeniero** [comment]
I'm using now SBT 1.3.10, so this is now irrelevant.
