### ISSUE TITLE
`provided` dependencies not on `run` classpath

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt#3733]
(See the guidelines for contributing, linked above)

## steps

[Repro repo](https://github.com/ryan-williams/scala-bugs/tree/provided)

Setup:

```bash
git clone git@github.com:ryan-williams/scala-bugs.git
cd scala-bugs
git checkout provided
```

Tests get `provided` dependencies on the classpath:

```bash
sbt test  # runs fine
```

as does console:

```bash
sbt console
```
```scala
scala> new org.apache.spark.SparkConf  // works fine
```

but `run` does not:

```bash
sbt run
…
[error] (run-main-0) java.lang.NoClassDefFoundError: org/apache/spark/SparkConf
[error] java.lang.NoClassDefFoundError: org/apache/spark/SparkConf
[error] 	at Main$.main(Main.scala:5)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
…
```

### Files

`build.sbt`:

```scala
scalaVersion := "2.11.11"
libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.2.0" % "provided",
  "org.scalatest" %% "scalatest" % "3.0.0" % "test"
)
```

`src/main/scala/Main.scala`:

```scala
object Main {
  def main(args: Array[String]): Unit = {
    println(new org.apache.spark.SparkConf())
  }
}
```

`src/test/scala/Test.scala`:

```scala
class Test extends org.scalatest.FunSuite {
  test("test") {
    println(new org.apache.spark.SparkConf())
  }
}
```

## problem

`sbt run` crashes

## expectation

`sbt run` should get `provided` dependencies on the classpath

## notes

also discussed in [this SO](https://stackoverflow.com/questions/18838944/how-to-add-provided-dependencies-back-to-run-test-tasks-classpath/28200761#28200761)

sbt version: 1.0.3

**Comment by ravwojdyla** [comment]
PTAL: https://github.com/sbt/zinc/pull/473

**Comment by eed3si9n** [comment]
Zinc fix is now merged. Please try sbt 1.1.0-RC3.

**Comment by mhamilton723** [comment]
@eed3si9n This is still affecting my build with 1.1.0. Are you sure it is fixed?

**Comment by eed3si9n** [comment]
@mhamilton723 Thanks for letting us know. I can confirm that this is still an issue.

**Comment by oripwk** [comment]
Is there anything new about it? I'm using sbt 1.2.8 and still experiencing this issue.

Is there any workaround? (apart from manually changing the scope every time)

**Comment by manu-crealytics** [comment]
As workaround, this works for me on 1.3.0:
```
Runtime / fullClasspathAsJars := (Test / fullClasspathAsJars).value
```

Got the inspiration from https://github.com/sbt/sbt/blob/v1.3.0/main/src/main/scala/sbt/Defaults.scala#L1632

**Comment by mkurz** [comment]
This is still not working in sbt 1.3.8... (no matter if using coursier or not, if this is even relevant).

**Comment by OlegYch** [comment]
run should use same deps as console, and both should have provided deps in classpath, otherwise who's going to 'provide' them

**Comment by eatkins** [comment]
I'm not sure that I agree that provided dependencies should automatically be added to the runtime classpath because often the whole point of provided dependencies is that they should only be available if the runtime context has them. You may want the application to _not_ use the provided the dependency if it isn't available. This use case is supported by sbt at the moment and would not be if provided dependencies were automatically added to the classpath.

That being said, the following doesn't work:
```
libraryDependencies += "com.swoval" % "file-tree-views" % "2.1.2" % "provided"
Runtime / libraryDependencies += "com.swoval" % "file-tree-views" % "2.1.2"
```
If I then run,`show Runtime / fullClasspath`, I get:
```
sbt:provided> show Runtime / fullClasspath
[info] * Attributed($PROJECTDIR/provided/target/scala-2.12/classes)
[info] * Attributed($USERDIR/.sbt/boot/scala-2.12.10/lib/scala-library.jar)
```
but if I run `show Runtime / libraryDependencies`, I get:
```
sbt:provided> show Runtime / libraryDependencies
[info] * org.scala-lang:scala-library:2.12.10
[info] * com.swoval:file-tree-views:2.1.2:provided
[info] * com.swoval:file-tree-views:2.1.2
```
It seems to me that here the non-provided dependency should win and show up in the `Runtime / fullClasspath` but it doesn't for whatever reason.

**Comment by OlegYch** [comment]
@eatkins don't think libdeps setting is (or should be) scoped in any way, it would be way too complicated if it was (considering each separate dep already has a maven scope)
ie there is no reasonable way to interpret eg `Compile / libraryDependencies += something % "test"`

**Comment by OlegYch** [comment]
@eatkins i'd guess run deps differing from console is an oversight or legacy compatibility decision
as far as i can see it hurts spark users (see eg https://github.com/JetBrains/intellij-scala/wiki/%5BSBT%5D-How-to-use-provided-libraries-in-run-configurations), and wouldn't hurt anyone if they were made equal, though extra care will be needed to ensure sbt-assembly and similar are not affected
