### ISSUE TITLE
"sbt '++ 2.13.0-M2!' compile" does not work with sbt 1.0.0

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#3427]
## steps

- https://github.com/xuwei-k/sbt-1-cross-bug
- https://travis-ci.org/xuwei-k/sbt-1-cross-bug/builds/263752411

project/build.properties

```
sbt.version=1.0.0
```

build.sbt

```scala
scalaVersion := "2.12.3"
```

Foo.scala

```scala
package example

class Foo
```

execute `sbt '++ 2.13.0-M2!' compile`

## problem

```
[info] Forcing Scala version to 2.13.0-M2 on all projects.
[info] Reapplying settings...
[info] Set current project to sbt-1-cross-bug (in build file:/home/travis/build/xuwei-k/sbt-1-cross-bug/)
[info] Updating {file:/home/travis/build/xuwei-k/sbt-1-cross-bug/}sbt-1-cross-bug...
[info] Done updating.
[info] Compiling 1 Scala source to /home/travis/build/xuwei-k/sbt-1-cross-bug/target/scala-2.13.0-M2/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.13.0-M2. Compiling...
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:11: error: object ILoop is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.{ ILoop, IMain, InteractiveReader }
       ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:41: error: not found: type ILoop
    val loop = new ILoop {
                   ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:44: error: not found: value in
          in = InteractiveReader.apply()
          ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:45: error: not found: value intp
          intp = new IMain(settings) {
          ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:52: error: not found: value intp
          intp.setContextClassLoader()
          ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:54: error: value createInterpreter is not a member of AnyRef
          super.createInterpreter()
                ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:57: error: not found: value intp
          intp.beQuietDuring(intp.bind(id, value.asInstanceOf[AnyRef].getClass.getName, value))
          ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:57: error: not found: value intp
          intp.beQuietDuring(intp.bind(id, value.asInstanceOf[AnyRef].getClass.getName, value))
                             ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:60: error: not found: value intp
          intp.interpret(initialCommands)
          ^
/tmp/sbt_a4c7a1d5/xsbt/ConsoleInterface.scala:67: error: not found: value intp
          intp.interpret(cleanupCommands)
          ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleHelper.scala:10: error: object IR is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.IR
       ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleHelper.scala:14: error: not found: value IR
  implicit def toConsoleResult(ir: IR.Result): InteractiveConsoleResult =
                                   ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleHelper.scala:16: error: not found: value IR
      case IR.Success    => InteractiveConsoleResult.Success
           ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleHelper.scala:17: error: not found: value IR
      case IR.Incomplete => InteractiveConsoleResult.Incomplete
           ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleHelper.scala:18: error: not found: value IR
      case IR.Error      => InteractiveConsoleResult.Error
           ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleInterface.scala:41: error: type mismatch;
 found   : java.io.PrintWriter
 required: scala.tools.nsc.interpreter.ReplReporter
  val interpreter: IMain = new IMain(compilerSettings, new PrintWriter(outWriter)) {
                                                       ^
/tmp/sbt_a4c7a1d5/xsbt/InteractiveConsoleInterface.scala:48: error: type mismatch;
 found   : tools.nsc.interpreter.Results.Result
 required: xsbti.InteractiveConsoleResult
    InteractiveConsoleResponse(r, outWriter.toString)
                               ^
17 errors found
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.0.0.
[info] downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.0.0/compiler-bridge_2.12-1.0.0-sources.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt#compiler-bridge_2.12;1.0.0!compiler-bridge_2.12.jar(src) (35ms)
[error] (compile:compileIncremental) Error compiling the sbt component 'compiler-bridge_2.12'
[error] Total time: 19 s, completed Aug 12, 2017 5:48:00 AM
```

## expectation

compile success

## notes

sbt version: 1.0.0

**Comment by xuwei-k** [comment]
Note: sbt 0.13.16 with Scala 2.13.0-M2 works because sbt 0.13.16's ConsoleInterface does not use ILoop
https://github.com/sbt/sbt/blob/v0.13.16/compile/interface/src/main/scala/xsbt/ConsoleInterface.scala

**Comment by SethTisue** [comment]
I discovered this myself the other day as well. sbt 1.0.x does not support Scala 2.13.0-Mx.

**Comment by SethTisue** [comment]
@eed3si9n a bit sad to see this pushed to 1.0.4, but I assume you're doing what you need to do. would you care to guess how long it might be before 1.0.4 comes out...?

**Comment by eed3si9n** [comment]
Theoretically, we ship hotfixes as often as we get fixes merged. We've been accumulating a bunch of fixes, so 1.0.3 needs to ship like today. 1.0.4 can follow up next week if someone spends 1h on this fix.

**Comment by eed3si9n** [comment]
I am trying to fix this, and I am hitting this bug in sbt 1.0.2

```
sbt:Compiler Bridge> compile
[info] Compiling 23 Scala sources to /Users/eed3si9n/work/sbt-modules/zinc/internal/compiler-bridge/target/scala-2.13.0-M2/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.13.0-M2. Compiling...
/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_b0ec940a/xsbt/ConsoleInterface.scala:11: error: object ILoop is not a member of package scala.tools.nsc.interpreter
import scala.tools.nsc.interpreter.{ ILoop, IMain, InteractiveReader, NamedParam }
       ^
```

so I probably need to patch the Zinc build somehow.

**Comment by dwijnand** [comment]
Are you referring to "Non-compiled module 'compiler-bridge_2.12' for Scala 2.13.0-M2"? Cos that looks like the wrong part.

**Comment by xuwei-k** [comment]
workaround https://gist.github.com/xuwei-k/58b082737d564b4720b850045cf7b5a9

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/453 / https://github.com/sbt/sbt/pull/3768
