### PR TITLE
Set currentRun and currentUnit in Eval

### LINKED ISSUE #1181: errors found in build.sbt are reported with no position (java.lang.ArrayIndexOutOfBoundsException: -1)
This build.sbt:

```
lazy val bob = scala.Console println
```

Will crash sbt with no indication whatsoever what happened, where or why. (My real one is more than one line.) The expression is valid scala.

```
[info] Loading project definition from /Users/paulp/scratch/2014-03-12_sbt_1/project
java.lang.ArrayIndexOutOfBoundsException: -1
    at scala.reflect.internal.util.OffsetPosition.column(Position.scala:249)
    at scala.reflect.internal.util.Position$.formatMessage(Position.scala:33)
    at scala.tools.nsc.reporters.ConsoleReporter.printMessage(ConsoleReporter.scala:49)
    at scala.tools.nsc.reporters.ConsoleReporter.print(ConsoleReporter.scala:52)
    at scala.tools.nsc.reporters.ConsoleReporter.display(ConsoleReporter.scala:78)
    at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:49)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
```

The "full log", or at least it is so implied:

```
[error] java.lang.ArrayIndexOutOfBoundsException: -1
[error] Use 'last' for the full log.
[debug] > load-failed
[debug] > last
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

If the implied empty param list is given, it compiles.

```
lazy val bob = scala.Console println ()
```

### LINKED ISSUE #1501: Missing , in .sbt leads to ArrayIndexOutOfBoundsException
## steps

Create a `build.sbt` ::

``` scala
val depA = "org.scala-lang" % "scala-reflect" % "2.10.4"

val depB = "org.scala-lang" % "scala-compiler" % "2.10.4"


libraryDependencies ++= Seq(
  depA
  depB
)
```
## problem

Start sbt, get:

```
$ sbt
[info] Loading global plugins from /home/jsuereth/.sbt/0.13/plugins
[warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Loading project definition from /home/jsuereth/projects/sbt/diagnose/crash-report/project
[warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
java.lang.ArrayIndexOutOfBoundsException: -1
    at scala.reflect.internal.util.OffsetPosition.column(Position.scala:249)
    at scala.reflect.internal.util.Position$.formatMessage(Position.scala:33)
    at scala.tools.nsc.reporters.ConsoleReporter.printMessage(ConsoleReporter.scala:49)
    at scala.tools.nsc.reporters.ConsoleReporter.print(ConsoleReporter.scala:52)
    at scala.tools.nsc.reporters.ConsoleReporter.display(ConsoleReporter.scala:78)
    at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:49)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
    at scala.tools.nsc.reporters.Reporter.withoutTruncating(Reporter.scala:42)
    at scala.tools.nsc.reporters.Reporter.error(Reporter.scala:70)
    at scala.tools.nsc.CompilationUnits$CompilationUnit.error(CompilationUnits.scala:102)
    at scala.tools.nsc.typechecker.Contexts$Context.scala$tools$nsc$typechecker$Contexts$Context$$unitError(Contexts.scala:390)
    at scala.tools.nsc.typechecker.Contexts$Context$$anonfun$issue$1.applyOrElse(Contexts.scala:402)
    at scala.tools.nsc.typechecker.Contexts$Context$$anonfun$issue$1.applyOrElse(Contexts.scala:401)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.NotAMemberError(ContextErrors.scala:350)
    at scala.tools.nsc.typechecker.Typers$Typer.handleMissing$1(Typers.scala:4841)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedSelect$1(Typers.scala:4846)
    at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4933)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5563)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedArgToPoly$1(Typers.scala:3418)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$70.apply(Typers.scala:3426)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$70.apply(Typers.scala:3426)
    at scala.reflect.internal.util.Collections$class.map2(Collections.scala:51)
    at scala.reflect.internal.SymbolTable.map2(SymbolTable.scala:13)
    at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3426)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3438)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4627)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4659)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5564)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedArgToPoly$1(Typers.scala:3418)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$70.apply(Typers.scala:3426)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$70.apply(Typers.scala:3426)
    at scala.reflect.internal.util.Collections$class.map2(Collections.scala:51)
    at scala.reflect.internal.SymbolTable.map2(SymbolTable.scala:13)
    at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3426)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3438)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4627)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4659)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5564)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5845)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2257)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1919)
    at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1800)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5584)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5301)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5587)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5704)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:99)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:91)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply$mcV$sp(Eval.scala:159)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply(Eval.scala:159)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply(Eval.scala:159)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at sbt.compiler.Eval.compile$1(Eval.scala:159)
    at sbt.compiler.Eval.compileAndLoad(Eval.scala:164)
    at sbt.compiler.Eval.evalCommon(Eval.scala:135)
    at sbt.compiler.Eval.eval(Eval.scala:86)
    at sbt.EvaluateConfigurations$.evaluateSetting(EvaluateConfigurations.scala:144)
    at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:106)
    at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:105)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:105)
    at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:507)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:502)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:501)
    at scala.Option.getOrElse(Option.scala:120)
    at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:501)
    at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
    at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Load$.loadSettings$1(Load.scala:500)
    at sbt.Load$.sbt$Load$$expand$1(Load.scala:523)
    at sbt.Load$.loadSettings(Load.scala:528)
    at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
    at sbt.Load$.defaultLoad$1(Load.scala:475)
    at sbt.Load$.loadTransitive(Load.scala:478)
    at sbt.Load$.loadProjects$1(Load.scala:418)
    at sbt.Load$.loadUnit(Load.scala:419)
    at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
    at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
    at sbt.BuildLoader.apply(BuildLoader.scala:143)
    at sbt.Load$.loadAll(Load.scala:312)
    at sbt.Load$.loadURI(Load.scala:264)
    at sbt.Load$.load(Load.scala:260)
    at sbt.Load$.load(Load.scala:251)
    at sbt.Load$.apply(Load.scala:134)
    at sbt.Load$.defaultLoad(Load.scala:37)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$.process(Command.scala:95)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
    at sbt.State$$anon$1.process(State.scala:179)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(MainLoop.scala:100)
    at sbt.MainLoop$.run(MainLoop.scala:93)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
    at sbt.MainLoop$.runLogged(MainLoop.scala:25)
    at sbt.StandardMain$.runManaged(Main.scala:57)
    at sbt.xMain.run(Main.scala:29)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:19)
    at xsbt.boot.Boot$.runImpl(Boot.scala:44)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ArrayIndexOutOfBoundsException: -1
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```
## expectations

The user should get a legitimate warning.
## notes

Likely related #1181

### LINKED ISSUE #1523: Sbt can't build with Scala 2.11
The workaround implemented in #1509 breaks sbt build with Scala 2.11. The failure is:

```
[error] /localhome/jenkinsdbuild3/workspace/Community-2.11.x/target-0.9.1/project-builds/sbt-85b2a717c4973e098c7eb55d9d90dcbd2011dbb2/main/actions/src/main/scala/sbt/compiler/Eval.scala:355: overriding method error in class CompilationUnit of type (pos: Eval.this.global.Position, msg: String)Unit;
[error]  method error cannot override final member
[error]     override def error(pos0: Position, msg: String) = {
[error]                  ^
[error] one error found
[error] (actions/compile:compile) Compilation failed
```

The work-around is being broken by scala/scala#3820 and scala/scala#3868.

We could make the `CompilationUnit.errror` method non-final but that would just obfuscate the fact that the work-around from #1509 is not working anymore. Compiler internals do not call `CompilationUnit.error` anymore so overriding that method doesn't let you intercept reported errors (and their positions).

### PR DESCRIPTION
**Pull request by gkossakowski**
First of all, we revert changes to Eval made in
a9cdd96152e08a1fb21e815eabe8fd1d27ef9b97. That was a work-around
for problem with broken positions set on some trees. The rest of
the commit describes a fix.

Scala compiler's Global has `currentRun` method which is supposed to
return an instance of Run currently in use. Sbt's Eval which wraps
Global would create an instance of Run but not register it in Global.
Similarly, Eval would create an instance of `CompilationUnit` but not
set it in Run.

This would result in some silent failures like assigning broken positions
to parsed trees even if parser _has_ received an instance of compilation
unit. See https://issues.scala-lang.org/browse/SI-8794 for details.

We fix the issue by subclassing Global and making it possible to set
current Run instance externally. Then we use this capability to set a run
instance right before we call compiler phases. We also make sure that
current run has current compilation assigned to it.

Fixes #1181
Fixes #1501
Fixes #1523

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @eed3si9n.

**Comment by gkossakowski** [comment]
//cc @paulp

**Comment by typesafe-tools** [comment]
Can one of the admins verify this patch?

**Comment by jsuereth** [comment]
LGTM cc @eed3si9n

**Comment by eed3si9n** [comment]
Much better fix than mine. Hats off to you.

**Comment by gkossakowski** [comment]
Thanks!
