### ISSUE TITLE
When `managedScalaInstance := false` and a scala library is in the dependencies, the compilation fails since 1.12.0

### ISSUE THREAD

**Issue by azdrojowa123** [sbt/sbt#9105]
## steps

1. Have this `build.sbt`: 
```
ThisBuild / scalaVersion := "2.13.16"

lazy val root = project.settings(
  autoScalaLibrary := false,
  managedScalaInstance := false,
  ivyConfigurations += Configurations.ScalaTool,
  libraryDependencies ++= Seq(
    "org.scala-lang" % "scala-library" % "2.13.16",
    "org.scala-lang" % "scala-compiler" % "2.13.16" % "scala-tool"
  )
)
```
Set sbt version to 1.11.7 in the project. Add some scala code to the `root` project. 

2. Start the sbt shell. 

3. Check the `scalaInstance` in the `root` project -> it's present. 

<img width="1124" height="105" alt="Image" src="https://github.com/user-attachments/assets/2604872b-430a-475f-ada0-96fbfb157c1b" />

4. Run `root/compile`. 

**Expected & actual result**: the sources are compiled 

5. Change the sbt version to 1.12.0 
6. Check the `scalaInstance` in the `root` project -> it's set to 0.0.0. 
`[info] Scala instance { version label 0.0.0, actual version 0.0.0, library jars: , compiler jars: , other jars:  }`
It's kind of expected because since [this commit](https://github.com/sbt/sbt/commit/ed7da85ef012b71919c8ce35b5e46c760db7766a), all projects with unmanaged scala instances have this empty scala instance with version 0.0.0
7. Run `root/compile`. 

**Expected**: the sources are compiled 
**Actual**: the compilation fails with exception: 

```
[info] compiling 1 Scala source to /Users/azdrojowa/IdeaProjects/sbt-demo/myTest/root/target/scala-2.13/classes ...
[error] ## Exception when compiling 1 sources to /Users/azdrojowa/IdeaProjects/sbt-demo/myTest/root/target/scala-2.13/classes
[error] java.lang.NoClassDefFoundError: scala/collection/IterableOnceOps
[error] java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
[error] java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:2991)
[error] java.base/java.lang.Class.getConstructor0(Class.java:3186)
[error] java.base/java.lang.Class.getConstructor(Class.java:2205)
[error] java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:623)
```
I did not investigate this further, but it looks like the compile task may not have the Scala jars (?). 
Maybe it's somehow related to this empty `scalaInstance`.

**Comment by eed3si9n** [comment]
@azdrojowa123  Thanks for the report!

On the sbt 2.x side I think the change was introduced in https://github.com/sbt/sbt/pull/8238, which may have been too aggressive. To support your example, which also is documented in sbt 1.x manual (https://www.scala-sbt.org/1.x/docs/Configuring-Scala.html), we should conditionally bring back the construction of scalaInstanceFromUpdate when `Configurations.ScalaTool` is available.

**Comment by azdrojowa123** [comment]
> we should conditionally bring back the construction of scalaInstanceFromUpdate when Configurations.ScalaTool is available.

It would be great to have this. Yesterday, I created a ticket in the Scala plugin (https://youtrack.jetbrains.com/issue/SCL-25316) to handle the case where Scala is unmanaged but set up correctly, and `scalaInstance` is returned with version 0.0.0, because we rely on `scalaInstance` to create a Scala SDK in IntelliJ. I started thinking about how to solve this and stop relying on `scalaInstance` in these cases, but if `scalaInstanceFromUpdate` is reverted, I think no workaround will be needed.

**Comment by eed3si9n** [comment]
I have a PR for this - https://github.com/sbt/sbt/pull/9121

**Comment by azdrojowa123** [comment]
Great, thank you :)
