### ISSUE TITLE
[1.3.0-RC1] [1.3.0-RC2] failed project load with global plugins and multiple meta projects

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4857]
## steps

~/.sbt/1.0/plugins/plugins.sbt:
```
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
```
./project/plugins.sbt
```
lazy val meta1 = project
dependsOn(meta1)
```
./project/build.properties
```
sbt.version=1.3.0-RC2
```

## problem

```
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.dwijnand:sbt-compat:1.2.6 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.6
[error]   Not found
[error]   not found: C:\Users\OlegYch\.ivy2\local\com.dwijnand\sbt-compat\scala_2.12\sbt_1.0\1.2.6\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:227)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$30(CoursierDependencyResolution.scala:196) [error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:196)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:87)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:137)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:150)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:150)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:131)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:164)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2844)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:279)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (meta1 / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.6
[error]   Not found
[error]   not found: C:\Users\OlegYch\.ivy2\local\com.dwijnand\sbt-compat\scala_2.12\sbt_1.0\1.2.6\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.2.6/sbt-compat-1.2.6.pom
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## expectation

project is loaded and global plugins work

## older steps
sbt version: 1.3.0-RC1 and 1.3.0-RC2
add an additional project in meta build and use global plugins  or just use the following `project/plugins.sbt`:
```
lazy val meta1 = project.settings(
  addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
)
dependsOn(meta1)
```

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report.

**Comment by eed3si9n** [comment]
```scala
lazy val meta1 = project
  .settings(
    addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2"),
    sbtPlugin := true
  )
```

It looks like `sbtPlugin := true` will add the right resolvers for those.

**Comment by OlegYch** [comment]
@eed3si9n the problem is that doesn't work with global plugins

**Comment by OlegYch** [comment]
explicit addsbtplugin in sub-meta-project was just for minimized example

**Comment by eed3si9n** [comment]
So you are defining a plugin globally in `~/.sbt/` and using that from a subproject in metabuild?
 like:
 
```scala
lazy val meta1 = project.settings(
  somecustomkey := ???
)
dependsOn(meta1)
```

**Comment by OlegYch** [comment]
@eed3si9n no i only use global plugins for the tasks they provide in regular projects, but it does seem to work in sbt 1.2.8 (eg dependencyGraphMLFile key for this plugin)

**Comment by eed3si9n** [comment]
Looks like it's something to do with how sbt hooks up with lm-coursier or Coursier is loading the global plugins. I am kind of confused how it's failing as `meta1 / update`. /cc @alexarchambault

**Comment by alexarchambault** [comment]
The exact steps to reproduce aren't clear to me… Do you have an example of what you put in `~/.sbt`, and in the current sbt project?

**Comment by OlegYch** [comment]
@alexarchambault 
~/.sbt/1.0/plugins/plugins.sbt:
```
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
```
./project/plugins.sbt
```
lazy val meta1 = project
dependsOn(meta1)
```
./project/build.properties
```
sbt.version=1.3.0-RC2
```

**Comment by alexarchambault** [comment]
Still investigating, but FTR, the [coursier-based sbt launcher](https://github.com/coursier/sbt-extras/blob/master/sbt) seems to have the right repositories.

It seems there's some binary incompatibility down the line then:
```
[error] java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate(Lsbt/librarymanagement/DependencyResolution;Lsbt/librarymanagement/ModuleDescriptor;Lsbt/util/CacheStoreFactory;Ljava/lang/String;Lsbt/librarymanagement/UpdateConfiguration;Lscala/Function1;ZZZLsbt/librarymanagement/UnresolvedWarningConfiguration;Lsbt/librarymanagement/EvictionWarningOptions;ZLsbt/internal/librarymanagement/CompatibilityWarningOptions;Lsbt/util/Logger;)Lsbt/librarymanagement/UpdateReport;
[error]   at sbt.dependencygraph.DependencyGraphSbtCompat$.$anonfun$updateTask$5(DependencyGraphSbtCompat.scala:61)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]   at sbt.Execute.work(Execute.scala:289)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   at java.lang.Thread.run(Thread.java:745)
[error] (ivyReport / update) java.lang.NoSuchMethodError: sbt.internal.LibraryManagement$.cachedUpdate(Lsbt/librarymanagement/DependencyResolution;Lsbt/librarymanagement/ModuleDescriptor;Lsbt/util/CacheStoreFactory;Ljava/lang/String;Lsbt/librarymanagement/UpdateConfiguration;Lscala/Function1;ZZZLsbt/librarymanagement/UnresolvedWarningConfiguration;Lsbt/librarymanagement/EvictionWarningOptions;ZLsbt/internal/librarymanagement/CompatibilityWarningOptions;Lsbt/util/Logger;)Lsbt/librarymanagement/UpdateReport;
```

**Comment by OlegYch** [comment]
@alexarchambault yeah i'll report that later

**Comment by eed3si9n** [comment]
The following workaround still works with the revised reproduction though, correct?

```scala
lazy val meta1 = project
  .settings(
    sbtPlugin := true
  )
```

**Comment by eed3si9n** [comment]
I think traditionally sbt supplies global plugins through

https://github.com/sbt/sbt/blob/e2921e70d2bb1c3bfa9f8b0fef7b7d9e96279771/main/src/main/scala/sbt/Defaults.scala#L664-L670

and

https://github.com/sbt/sbt/blob/e2921e70d2bb1c3bfa9f8b0fef7b7d9e96279771/main/src/main/scala/sbt/internal/GlobalPlugin.scala#L63-L68

whereas this comment here mentions global-plugins

https://github.com/sbt/sbt/blob/e2921e70d2bb1c3bfa9f8b0fef7b7d9e96279771/main/src/main/scala/sbt/coursierint/CoursierInputsTasks.scala#L153-L154

**Comment by OlegYch** [comment]
@eed3si9n correct
> 
> 
> The following workaround still works with the revised reproduction though, correct?
> 
> ```scala
> lazy val meta1 = project
>   .settings(
>     sbtPlugin := true
>   )
> ```

**Comment by akozumpl** [comment]
I depend on the dependency graph plugin through an ~/.sbt config and get the same failure in sbt-1.3. The following workaround works here™:

> resolvers += Resolver.sbtPluginRepo("releases")

**Comment by vadimbakaev** [comment]
I've got the same error with `sbt.version = 1.3.12` and `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")`

**Comment by kurtrwall** [comment]
I'm getting this error with `addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")` and `sbt.version = 1.5.2`.
