### ISSUE TITLE
[sbt 0.13.15] += interference with sbt-buildinfo

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3132]
originally reported by @corruptmemory

## steps

```
buildInfoKeys += gitHeadCommit,
```

## problem

```
// output under 0.13.15:

$ sbt
[info] Loading global plugins from /home/jim/.sbt/0.13/plugins
[info] Updating {file:/home/jim/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/jim/typesafe/MetricMeta/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]   * com.typesafe.sbt:sbt-native-packager:0.7.4 -> 1.2.0-M8
[warn] Run 'evicted' to see detailed eviction warnings
[error] /home/jim/typesafe/MetricMeta/project/Common.scala:107: value taskValue is not a member of sbt.SettingKey[Option[String]]
[error]         buildInfoKeys += gitHeadCommit,
[error]                       ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

## expectation

Works.

## workaround

A likely workaround for sbt 0.13.15 is:

```scala
buildInfoKeys += BuildInfoKey(gitHeadCommit)
```

## notes

This is likely caused by https://github.com/sbt/sbt/pull/2943.
buildInfoKeys takes a Seq of `BuildInfoKey.Entry[_]`.

```scala
lazy val buildInfoKeys        = settingKey[Seq[BuildInfoKey.Entry[_]]]("Entries for build info.")
```

There's an implicit that goes from `SettingKey[A]` to `Entry[A]` here - https://github.com/sbt/sbt-buildinfo/blob/v0.7.0/src/main/scala/sbtbuildinfo/package.scala

According to [SbtGit](https://github.com/sbt/sbt-git/blob/v0.9.2/src/main/scala/com/typesafe/sbt/SbtGit.scala) the key is a setting key, which is consistent with the setting.

```scala
val gitHeadCommit = SettingKey[Option[String]]("git-head-commit", "The commit sha for the top commit of this project.")
```

We probably need to fix the macro in https://github.com/sbt/sbt/pull/2943 so LHS is expecting `Seq[Task[T]]`.

**Comment by dwijnand** [comment]
Looks like no one's ever written that: https://github.com/search?q=%22buildInfoKeys+%2B%3D+gitHeadCommit%22&type=Code&utf8=%E2%9C%93

**Comment by corruptmemory** [comment]
Depends on where you look: https://github.com/typesafehub/example-code-service/blob/master/build.sbt#L58 ;-P

This is so we can do sanity checking: http://example.lightbend.com/info
Highly recommended. :-)
