### ISSUE TITLE
[sbt 0.13.13] incorrect deprecated message

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#2818]
## steps

`build.sbt`

```scala
val x = SettingKey[Seq[Task[Int]]]("x")

val y = TaskKey[Int]("y")

x := Nil

y := 42

x <+= y
```

`project/plugin.sbt`

```scala
scalacOptions += "-deprecation"
```

`project/build.properties`

```
sbt.version=0.13.13
```

sbt 0.13.13 says follow

```
build.sbt:9: warning: `<+=` operator is deprecated. Use `lhs += { x.value }`.
x <+= y
  ^
```

I modified `build.sbt` and reload

```diff
- x <+= y
+ x += y.value
```

```
build.sbt:9: error: No implicit for Append.Value[Seq[sbt.Task[Int]], Int] found,
  so Int cannot be appended to Seq[sbt.Task[Int]]
x += y.value
  ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## problem

```Use `lhs += { x.value }` ``` is incorrect message.

## expectation

`x += y.taskValue` is right way in this case.

**Comment by csaltos** [comment]
For me `x.value` works with 0.13.3.

I was using this expression with 0.13.12 ->
`unmanagedSourceDirectories in Compile <+= baseDirectory( _ / "extra/src/main/scala" )`

Which now with 0.13.13 works with ->
`unmanagedSourceDirectories in Compile += (baseDirectory( _ / "extra/src/main/scala" )).value`

If I try to use `taskValue` instead of `value` I got the error `error: value taskValue is not a member of sbt.Def.Initialize[java.io.File]`

What's the difference ? ... it's the same case ?

**Comment by dwijnand** [comment]
@csaltos For you case you want 

``` scala
unmanagedSourceDirectories in Compile += (baseDirectory.value / "extra/src/main/scala")
```

**Comment by csaltos** [comment]
OK, good to know, that's even another variant, so the main goal here is how to explain when to use taskValue or value at the deprecation error message and if they are the same case or different cases of the usage of `<+=`

**Comment by NicolasRouquette** [comment]
What about `dependsOn`like this:

(0) Using the deprecated `dependsOn`:

``` sbt
lazy val zipFile = taskKey[File]("A zip file to be created as an artifact to be published")

lazy val makeZip = taskKey[Unit]("Create the contents of the zipFile")

publish <<= publish dependsOn makeZip
```

It is unclear whether it should be refactored as:

1) Using `.value`:

``` sbt
lazy val zipFile = taskKey[File]("A zip file to be created as an artifact to be published")

lazy val makeZip = taskKey[Unit]("Create the contents of the zipFile")

publish := {
  val _ = makeZip.value
  publish.value
}
```

2) Using `.taskValue`:

``` sbt
lazy val zipFile = taskKey[File]("A zip file to be created as an artifact to be published")

lazy val makeZip = taskKey[Unit]("Create the contents of the zipFile")

publish := {
  val _ = makeZip.taskValue
  publish.value
}
```

I think (1) is correct; however, @eed3si9n's comments make me wonder what's the criteria to use.

**Comment by eed3si9n** [comment]
The migration of `dependsOn` is documented here: http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+using+%2C++or

**Comment by NicolasRouquette** [comment]
Thanks @eed3si9n; this helps a lot; however, I'm still experiencing problems with tasks like `AetherKeys.aetherDeploy` that execute before the completion of their dependencies where I create file artifacts. I'm really baffled by this new behavior (for details, see: https://github.com/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/issues/1)

**Comment by eed3si9n** [comment]
<s>
I didn't study your specific situation, but generally preferred style is 

``` scala
publish := {
  val _ = makeZip.value
  publish.value
}
```

</s>

Another tricky part is that if you have input task, you have to use `evaluated` instead of `value` (I we have deprecation message for that too) - http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+with

**Comment by NicolasRouquette** [comment]
That's what I thought.

Can you confirm that the following is incorrect?

``` sbt
publish := {
  val _ = makeZip.taskValue
  publish.value
}
```

In my experience the above doesn't guarantee that `makeZip` will complete before `publish` starts.

Also are the following equivalent?

`publish := { val _ = makeZip.value; publish.value }`
`publish := publish.dependsOn(makeZip).value`

Is the difference only a matter of style or is there more to it?

I understand the 1st form is stylistically recommended; however, it could be error-prone because one could mistakenly type instead:

`publish := { val _ = makeZip.taskValue; publish.value }`

With the 2nd form, there's no ambiguity about what the intent is.

**Comment by eed3si9n** [comment]
Actually I take that back.
- Calling `.taskVaue` is not going evaluate the task, so it's not what you want.
- `publish := { val _ = makeZip.value; publish.value }` also wrong because it will execute both makeZip and publish tasks concurrently.
- `publish := publish.dependsOn(makeZip).value` should run makeZip and then run publish task.

See also http://www.scala-sbt.org/0.13/docs/Howto-Sequencing.html

**Comment by NicolasRouquette** [comment]
Wow, thanks @eed3si9n for this clarification.

Well, this explains some of the weirdnesses I've had since migrating to 0.13.13!
I have a bunch of incorrect dependency migrations to fix!

Regarding sequencing, I'm honestly perplexed by the example:

```
compilecheck in Compile := Def.sequential(
   compile in Compile,
  (scalastyle in Compile).toTask("")
).value
```

Why is there a `.toTask("")` ? 

Suppose instead we have something simple:

```
lazy val a = taskKey[Unit]("....")
lazy val b = taskKey[Unit]("...")
lazy val c = taskKey[Unit]("....")
```

Which is the correct setting?

`c := Def.Sequential(a,b).value`
`c := Def.Sequential(a,b.toTask("")).value`

**Comment by dwijnand** [comment]
`.toTask` converts an InputTask to a Task. `scalastyle` is an InputTask it would seem (not sure why).

**Comment by NicolasRouquette** [comment]
Ah, ok. 

Obviously, one can't use `Def.Sequential()` for something like this `a := a.dependsOn(b).value`; 
that is, `a := Def.Sequential(a,b).value` shouldn't even compile nor make any sense.

**Comment by dwijnand** [comment]
no, generally Def.sequential is used to define a brand new key, like `verify` or `release`.
