### ISSUE TITLE
community build 1.2.x pinned builds

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4887]
Current Community Builds for Scala 2.12.x runs using sbt 1.3.0-RC3.
However, some projects are pinned to sbt 1.2.8 due to build failures. We might uncover some bugs by looking into these pinned builds.
https://github.com/scala/community-builds/blob/5b6f2e0c3c0894137ca0c138f5b5164d1ad91e39/configs/community.dbuild

### genjavadoc

```
  ${vars.base} {
    name: "genjavadoc"
    uri:  ${vars.uris.genjavadoc-uri}
    // failed compilation on sbt 1.3.0-RC3; not investigated
    // [genjavadoc] [error] ## Exception when compiling 8 sources to /Users/tisue/community.212/target-0.9.16/project-builds/genjavadoc-6b88a0370f6ac590936bca7f545b84205dd0627f/plugin/target/scala-2.12/test-classes
    // [genjavadoc] [error] java.lang.NullPointerException
    // [genjavadoc] [error] scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.close(GenBCode.scala:101)
    extra.sbt-version: ${vars.sbt-1-2-version}
  }
```

I can't reproduce the issue.

### akka stream

```
  ${vars.base} {
    name: "akka-stream"
    uri:  ${vars.uris.akka-uri}
    // doc failures on sbt 1.3.0-RC1 or RC2; not investigated; we should try 1.3.0-RC3
    // Unexpected javac output: javadoc: error - invalid flag: --ignore-source-errors.
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### parboiled2

```
  ${vars.base} {
    name: "parboiled2"
    uri:  ${vars.uris.parboiled2-uri}
    // failed on sbt 1.3.0-RC3; not investigated
    // java.util.zip.ZipException: duplicate entry: LICENSE
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### http4s-parboiled2

```
  // dependency of http4s (it's their fork of parboiled2)
  ${vars.base} {
    name: "http4s-parboiled2"
    uri:  ${vars.uris.http4s-parboiled2-uri}
    // failed compilation on sbt 1.3.0-RC3; not investigated
    // java.util.zip.ZipException: duplicate entry: LICENSE
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### playframework

```
  ${vars.base} {
    name: "playframework"
    uri:  ${vars.uris.playframework-uri}
    // compilation failure on sbt 1.3.0-RC3; not investigated
    // error] Symbol 'type play.api.libs.ws.WSBodyWritables' is missing from the classpath
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### log4s

```
  ${vars.base} {
    name: "log4s"
    uri:  ${vars.uris.log4s-uri}
    extra.exclude: ["coreJS", "testingJS"]
    // failed tests on 1.3; not investigated
    extra.sbt-version: ${vars.sbt-1-2-version}
  }
```

### blaze

```
  // frozen (April 2019) at v0.14.0 tag since that's the version http4s wants
  ${vars.base} {
    name: "blaze"
    uri: ${vars.uris.blaze-uri}
    // failed extraction on 1.3.0-RC3; not investigated
    // [blaze] [error] (update) sbt.librarymanagement.ResolveException: Error downloading org.xerial.sbt:sbt-sonatype;sbtVersion=1.0;scalaVersion=2.12:1.1
    extra.sbt-version: ${vars.sbt-1-2-version}
  }
```

### play-webgoat

```
  ${vars.base} {
    name: "play-webgoat"
    uri: ${vars.uris.play-webgoat-uri}
    // compilation failure on 1.3; not investigated
    // object index is not a member of package views.html
    extra.sbt-version: ${vars.sbt-1-2-version}
    // not sure how this gets pulled in but it's just doc not code, I think?
    // so let's just ignore that it's missing
    check-missing: false
    deps.ignore: ["com.typesafe.play#play-omnidoc"]
  }
```

### circe

```
  // frozen (April 2019) at an April 2019 commit just before ScalaTest 3.1 upgrade
  ${vars.base} {
    name: "circe"
    uri:  ${vars.uris.circe-uri}
    // failed compilation on sbt 1.3.0-RC3; not investigated
    // Symbol 'type io.circe.java8.time.JavaTimeDecoders' is missing from the classpath
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### http4s

```
  // this is a big build with a ton of subprojects.  we needn't be shy
  // about disabling fragile ones, ones with obscure dependencies we don't have, etc.
  // frozen May 2019 at a May 2019 commit just before a blaze test started failing; I see
  // the failure in their own CI (perhaps it was a semantic merge conflict?), so probably
  // we'll be able to unfreeze promptly
  ${vars.base} {
    name: "http4s"
    uri:  ${vars.uris.http4s-uri}
    // compilation failure on sbt 1.3.0-RC3; not investigated
    // Symbol 'type org.http4s.json4s.jackson.Json4sJacksonInstances' is missing from the classpath.
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### sttp

```
  ${vars.base} {
    name: "sttp"
    uri:  ${vars.uris.sttp-uri}
    // compilation failure on 1.3; not investigated
    // Symbol 'type com.softwaremill.sttp.playJson.SttpPlayJsonApi' is missing from the classpath.
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### tsec

```
  // dependency of scala-pet-store
  // frozen (June 2019) at a June 2019 commit before some dependency bumps. it looks like the
  // kind of thing where it isn't worth us digging into. (tsec.hashing.bouncy.HasherTest failed)
  ${vars.base} {
    name: "tsec"
    uri:  ${vars.uris.tsec-uri}
    // on sbt 1.3.0-RC3, tsec.PasswordTest failed; not investigated
    extra.sbt-version: ${vars.sbt-1-2-version}
```

## sbt family

```
  // currently sbt and its modules are frozen and/or forked, since
  // sbt has its own dbuild-based "community build" so we don't need
  // to track the latest (and doing so would be fragile).  but,
  // we should move to newer tags from time to time.
```

We can ignore the following pins since we are aware of the issues, and fixed them.

### io

```
  ${vars.base} {
    name: "sbt-io"
    uri:  ${vars.uris.sbt-io-uri}
    // failed extraction on 1.3.0-RC3 (ResolveException on org.boris:pecoff4j:0.0.2.1);
    // see remarks at https://github.com/scala/community-builds/pull/909
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### util

```
  // using a slightly post v1.2.0 commit in order to get
  // https://github.com/sbt/util/pull/172 which fixes failing tests
  ${vars.base} {
    name: "sbt-util"
    uri:  ${vars.uris.sbt-util-uri}
    // failed extraction on 1.3.0-RC3 (ResolveException on org.boris:pecoff4j:0.0.2.1);
    // see remarks at https://github.com/scala/community-builds/pull/909
    extra.sbt-version: ${vars.sbt-1-2-version}
```

### lm

```
  ${vars.base} {
    name: "sbt-librarymanagement"
    uri:  ${vars.uris.sbt-librarymanagement-uri}
    // failed extraction on 1.3.0-RC3 (ResolveException on org.boris:pecoff4j:0.0.2.1);
    // see remarks at https://github.com/scala/community-builds/pull/909
```

**Comment by eed3si9n** [comment]
playframework seems to compile ok locally, stand-alone.
https://github.com/scala/community-builds/pull/938

**Comment by eatkins** [comment]
I suspect some of the issues, like the circe compilation issue, might be related to https://github.com/sbt/sbt/issues/4823 which is resolved by https://github.com/coursier/coursier/pull/1239.

Also, I think we can safely unpin io/util/lm. They all work locally for me.

**Comment by eatkins** [comment]
log4s also worked locally for me.

**Comment by eed3si9n** [comment]
> Also, I think we can safely unpin io/util/lm. They all work locally for me.

I think the issue with sbt family is that the multi repos break often, so it needs to be pinned to some tag anyway. Maybe after 1.3.0 ships we move the pin to that.

**Comment by eed3si9n** [comment]
genjavadoc did blow up with NullPointerException.

```
[genjavadoc] [error] java.lang.NullPointerException
[genjavadoc] [error] 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.close(GenBCode.scala:101)
[genjavadoc] [error] 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:83)
[genjavadoc] [error] 	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:78)
[genjavadoc] [error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1503)
[genjavadoc] [error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
[genjavadoc] [error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1480)
[genjavadoc] [error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1606)
[genjavadoc] [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[genjavadoc] [error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[genjavadoc] [error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[genjavadoc] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[genjavadoc] [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[genjavadoc] [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[genjavadoc] [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[genjavadoc] [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[genjavadoc] [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[genjavadoc] [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[genjavadoc] [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[genjavadoc] [error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[genjavadoc] [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[genjavadoc] [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[genjavadoc] [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[genjavadoc] [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[genjavadoc] [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[genjavadoc] [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[genjavadoc] [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[genjavadoc] [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1686)
[genjavadoc] [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1659)
[genjavadoc] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[genjavadoc] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[genjavadoc] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[genjavadoc] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[genjavadoc] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[genjavadoc] [error] 	at sbt.Execute.work(Execute.scala:289)
[genjavadoc] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[genjavadoc] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[genjavadoc] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[genjavadoc] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[genjavadoc] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[genjavadoc] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[genjavadoc] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[genjavadoc] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[genjavadoc] [error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eed3si9n** [comment]
I'm seeing Play fail consistently on Community Build but not locally.

```
[playframework] [error] Symbol 'type play.api.libs.ws.WSBodyWritables' is missing from the classpath.
[playframework] [error] This symbol is required by 'package play.api.libs.ws.package'.
[playframework] [error] Make sure that type WSBodyWritables is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[playframework] [error] A full rebuild may help if 'package.class' was compiled against an incompatible version of play.api.libs.ws.
[playframework] [error] one error found
...
[playframework] [error] (Play-WS / Compile / compileIncremental) Compilation failed
```

sbt 1.3.0-RC3 uses lm-coursier-shaded 2.0.0-RC2-1 (coursier 2.0.0-RC2-6), which should contain the fixes made in https://github.com/coursier/coursier/pull/1239.

**Comment by eed3si9n** [comment]
I ran Community Build with `-Dsbt.coursier=false` for the currently-pinned builds
https://github.com/scala/community-builds/compare/68169c0...eed3si9n:wip/coursier-false?expand=1
and the results are here - https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/4719/console

```
[info] ---==  Execution Report ==---
[info] Report from the dbuild run for dbuild: 
[info] Project circe-----------------------: FAILED (RuntimeException: )
[info] Project circe-config----------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project circe-derivation------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project circe-jackson---------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project http4s----------------------: DID NOT RUN (stuck on broken dependencies: circe, http4s-parboiled2)
[info] Project http4s-parboiled2-----------: FAILED (RuntimeException: )
[info] Project kafka-----------------------: SUCCESS (project rebuilt ok)
[info] Project play-webgoat----------------: DID NOT RUN (stuck on broken dependencies: playframework)
[info] Project playframework---------------: FAILED (RuntimeException: )
[info] Project sttp------------------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project tsec------------------------: DID NOT RUN (stuck on broken dependencies: circe, http4s-parboiled2)

[info] >>> The dbuild result is----------------: FAILED (failed: mima, http4s-parboiled2, akka-persistence-cassandra, monix, playframework, circe, zinc)
```

The only build that improved was Kafka, and circe and playframework are still broken.

### circe

```
[circe] [error] Symbol 'type io.circe.java8.time.JavaTimeDecoders' is missing from the classpath.
[circe] [error] This symbol is required by 'package io.circe.java8.time.package'.
[circe] [error] Make sure that type JavaTimeDecoders is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[circe] [error] A full rebuild may help if 'package.class' was compiled against an incompatible version of io.circe.java8.time.
[circe] [error] Symbol 'type io.circe.java8.time.JavaTimeEncoders' is missing from the classpath.
[circe] [error] This symbol is required by 'package io.circe.java8.time.package'.
[circe] [error] Make sure that type JavaTimeEncoders is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[circe] [error] A full rebuild may help if 'package.class' was compiled against an incompatible version of io.circe.java8.time.
[circe] [error] two errors found
```

### playframework

```
[playframework] [error] Symbol 'type play.api.libs.ws.WSBodyWritables' is missing from the classpath.
[playframework] [error] This symbol is required by 'package play.api.libs.ws.package'.
[playframework] [error] Make sure that type WSBodyWritables is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[playframework] [error] A full rebuild may help if 'package.class' was compiled against an incompatible version of play.api.libs.ws.
[playframework] [error] one error found
```

**Comment by dwijnand** [comment]
I'm getting that Play-WS errors locally with 1.2.8.  So it seems to be a pre-existing incremental compiler bug (IIUC).

**Comment by eed3si9n** [comment]
@dwijnand I've split that one out as a Zinc issue - https://github.com/sbt/zinc/issues/690

**Comment by eatkins** [comment]
That's useful data. The circe issue also looks it might be the same incremental compilation issue as https://github.com/sbt/zinc/issues/690. The design pattern of JavaTimeDecoders and the io.circe.time package object is the same as play.api.libs.ws and play.api.libs.ws.WSBodyWritables. Maybe we should re-run the community build with "-Ylog-classpath"? I don't know if that will be helpful.

**Comment by eed3si9n** [comment]
Yea. Unless we regressed somehow in Zinc, I don't understand why we are hitting this package object bug more consistently in 1.3.0-RCs.

**Comment by eatkins** [comment]
I don't understand it either. @dwijnand I'm guessing that you don't see the issue every time with 1.2.8?

**Comment by dwijnand** [comment]
No, not every compile requires `clean`ing to make it work, just from time to time.  Maybe 1/10 times.  Oh, and this is while iterating in another part of the code base.  Feels to me like a race condition, maybe?  Like that `classes.bak` bug.

**Comment by eed3si9n** [comment]
@SethTisue let me know that Doodle and Mima are joining the pinned camp.

### Doodle

```
  ${vars.base} {
    name: "doodle"
    uri: ${vars.uris.doodle-uri}
    // [doodle] [error] Symbol 'type doodle.explore.syntax.ExploreSyntax' is missing from the classpath.
    extra.sbt-version: ${vars.sbt-1-2-version}
    extra.projects: [
      "coreJVM", "java2d", "exploreJVM", "imageJVM", "turtleJVM"  // no Scala.js plz
    ]
    extra.commands: ${vars.default-commands} [
      // sbt 1.3.0-RC3 specific: Credentials file [...] does not exist
      "set every credentials := Seq()"
    ]
  }
```

### Mima

```
  ${vars.base} {
    name: "mima"
    uri:  ${vars.uris.mima-uri}
    // [error] java.lang.NoClassDefFoundError: xsbt/ZincCompiler$sbtDependency$
    extra.sbt-version: ${vars.sbt-1-2-version}
    extra.exclude: [
      // we don't compile sbt plugins
      "sbtplugin"
      // TODO remove exclusion once Scala 2.12.9 comes out, as per
      // https://github.com/lightbend/mima/issues/355
      "test-value-class-generic-replacement-false-ok"
    ]
    extra.options: ["-Xmx4g"]
    // ignore missing scripted-sbt (https://github.com/sbt/sbt/issues/3917 ?)
    deps.ignore: ["org.scala-sbt#scripted-sbt"]
    check-missing: false
  }
```

**Comment by eed3si9n** [comment]
Kafka is now builds on sbt 1.3.0-RC3 - https://github.com/scala/community-builds/pull/951#issuecomment-519251497

**Comment by eed3si9n** [comment]
In https://github.com/scala/community-builds/issues/966#issuecomment-523564364 @SethTisue wrote:

> the full list of projects that didn't work on RC4 is:
> 
> - fs2 (worked on RC3)
> - genjavadoc
> - scala-js
> - blaze
> - sbt-io, sbt-util, sbt-librarymanagement (very old versions)
> - sttp
> - tsec

https://github.com/scala/community-builds/blob/178fe829711d7fac1d2ac5b82dda3a981116929a/configs/community.dbuild

So it looks like RC4 has fixed:

- akka-stream
- parboiled2
- http4s-parboiled2
- playframework
- log4s
- play-webgoat
- circe
- http4s
- Dooble
- Mima

**Comment by SethTisue** [comment]
should this ticket remain open?

**Comment by eed3si9n** [comment]
Now that 1.3.0 is out, I am happy to close this out.
