### ISSUE TITLE
NoClassDefFoundError: io/netty/channel/unix/UnixChannelOption in Play apps

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4823]
## steps
sbt version: 1.3.0-RC2

I've failed to reproduce this locally, but it has failed multiple times (like 10+) in multiple apps in Travis CI so I'm reporting it anyways.

See the failures in https://github.com/playframework/play-samples/pull/29, e.g. https://travis-ci.com/playframework/play-samples/jobs/208339896

## problem

```
[error] Test BrowserTest.test failed: java.lang.NoClassDefFoundError: io/netty/channel/unix/UnixChannelOption, took 4.356 sec
[error]     at play.core.server.NettyServer.initializeChannelOptionsStaticMembers(NettyServer.scala:314)
[error]     at play.core.server.NettyServer.<init>(NettyServer.scala:63)
[error]     at play.core.server.NettyServerProvider.createServer(NettyServer.scala:340)
[error]     at play.core.server.NettyServerProvider.createServer(NettyServer.scala:332)
[error]     at play.core.server.ServerProvider.createServer(ServerProvider.scala:29)
[error]     at play.core.server.ServerProvider.createServer$(ServerProvider.scala:26)
[error]     at play.core.server.NettyServerProvider.createServer(NettyServer.scala:332)
[error]     at play.api.test.TestServer.start(TestServer.scala:46)
[error]     at play.test.WithServer.startServer(WithServer.java:49)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
[error] Caused by: java.lang.ClassNotFoundException: io.netty.channel.unix.UnixChannelOption
[error]     at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
[error]     at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]     ... 43 more
```

## expectation

Tests pass

## notes

In the different apps I've seen the "NoClassDefFoundError: io/netty/channel/unix/UnixChannelOption" error be provoked by a few different ways.

**Comment by eed3si9n** [comment]
The script says:

```bash
#!/usr/bin/env bash

set -e
set -o pipefail

echo "+----------------------------+"
echo "| Executing tests using sbt  |" 
echo "+----------------------------+"
sbt ++$TRAVIS_SCALA_VERSION test
```

so the repro steps is run `test`?

There's #4796, but probably not the same issue if it's not shutdown hooks related.

**Comment by dwijnand** [comment]
> so the repro steps is run `test`?

Yeah, but I'm not sure why it failed in Travis CI but not for me locally.

**Comment by eed3si9n** [comment]
I saw the following in the community build (https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/4588/), I think using M5:

```
[playframework] ** COMMUNITY BUILD LINE COUNT: 905
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-c2b158b3fc0c25276c34b9908bd23e7589766c32/transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala:27:25: object unix is not a member of package io.netty.channel
[playframework] [error] import io.netty.channel.unix.UnixChannelOption
[playframework] [error]                         ^
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-c2b158b3fc0c25276c34b9908bd23e7589766c32/transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala:157:30: Class io.netty.channel.unix.UnixChannel not found - continuing with a stub.
[playframework] [error]       case Native => classOf[EpollServerSocketChannel]
[playframework] [error]                              ^
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-c2b158b3fc0c25276c34b9908bd23e7589766c32/transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala:314:75: Class io.netty.channel.unix.UnixChannelOption not found - continuing with a stub.
[playframework] [error]     Seq(classOf[ChannelOption[_]], classOf[UnixChannelOption[_]], classOf[EpollChannelOption[_]]).foreach(clazz => {
[playframework] [error]                                                                           ^
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-c2b158b3fc0c25276c34b9908bd23e7589766c32/transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala:314:44: not found: type UnixChannelOption
[playframework] [error]     Seq(classOf[ChannelOption[_]], classOf[UnixChannelOption[_]], classOf[EpollChannelOption[_]]).foreach(clazz => {
[playframework] [error]                                            ^
[playframework] [error] four errors found
[playframework] [error] (Play-Netty-Server / Compile / compileIncremental) Compilation failed
```

I wonder if the class is actually missing somehow due to resolution difference etc?

**Comment by eatkins** [comment]
And this doesn't happen with RC1? If that's the case, I'm curious if the failures occur if you run the tests with `-Dsbt.classloader.close=false`. In RC1, the classloaders were not actually closed when tests completed but in RC2 they are.

**Comment by eatkins** [comment]
Going back to @eed3si9n's question about resolution I wonder if there is an older version of netty in the .ivy2 cache that is being used. The UnixChannelOption class is pretty new and was added in the patch version 4.1.11. If, for example, somehow netty transport is being resolved to 4.1.10, this would happen. This should be debuggable by changing the test-sbt script to:
```bash
#!/usr/bin/env bash

set -e
set -o pipefail

echo "+----------------------------+"
echo "| Executing tests using sbt  |" 
echo "+----------------------------+"
sbt ++$TRAVIS_SCALA_VERSION ";show Test / fullClasspath; test"
```

**Comment by dwijnand** [comment]
> And this doesn't happen with RC1?

Not necessarily, I'd seen too many troubling issues in RC1 to even suggest/consider testing it out, so this is testing from 1.2.8 to 1.3.0-RC2.

> I wonder if the class is actually missing somehow due to resolution difference etc?

> I wonder if there is an older version of netty in the .ivy2 cache that is being used.

Sounds plausible.  Do you think this should be reported to Coursier?

**Comment by eed3si9n** [comment]
so I ran the experiment @eatkins suggested here - https://travis-ci.org/eed3si9n/play-samples/jobs/548763360
and thankfully the bug is reproducible.

What's interesting is that

```
[info] * Attributed(/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar)
```

is found but `netty-transport-native-unix-common`, the module that defines [UnixChannelOption](https://github.com/netty/netty/blob/netty-4.1.34.Final/transport-native-unix-common/src/main/java/io/netty/channel/unix/UnixChannelOption.java) is missing from the classpath.
I am not sure if this is working as designed since Play 2.7.3 depends on the following:

https://github.com/playframework/playframework/blob/2.7.3/project/Dependencies.scala#L158-L160

```scala
  val netty = Seq(
    "com.typesafe.netty" % "netty-reactive-streams-http" % "2.0.3",
    ("io.netty" % "netty-transport-native-epoll" % nettyVersion).classifier("linux-x86_64")
```

and here's the POM file for it - http://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final.pom. Under Linux profile it says:

```xml
<dependencies>
  <dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-transport-native-unix-common</artifactId>
  <version>${project.version}</version>
  <classifier>${jni.classifier}</classifier>
   <!--

            The unix-common with classifier dependency is optional because it is not a runtime dependency, but a build time
            dependency to get the static library which is built directly into the shared library generated by this project.
          
  -->
  <optional>true</optional>
  </dependency>
</dependencies>
```

So if Play's source code is directly using `io.netty.channel.unix.UnixChannelOption`, I'd suggest Play depend on `netty-transport-native-unix-common` explicitly.

**Comment by dwijnand** [comment]
What does "to get the static library which is built directly into the shared library generated by this project" mean?  Why does it work with sbt 1.2.8?

**Comment by eed3si9n** [comment]
I don't know the build of Netty, but I am guessing it's analogous to Scala's compile-time only dependencies for macros. It's works with Ivy maybe because it was pulling in the optional dependency?

**Comment by dwijnand** [comment]
But it contains runtime classes (that are required) so how can it be compile-time only?

If this is a problem with Ivy and optional dependencies, perhaps sbt should have a general solution to help users upgrade to sbt 1.3 while requiring optional dependencies to be also pulled.

**Comment by eed3si9n** [comment]
As I see it, this is a regression in https://github.com/playframework/playframework/pull/9049 for mentioning UnixChannelOption, but not depending on netty-transport-native-unix-common. Maybe the class is compiled away because `UnixChannelOption` contains static finals - https://github.com/netty/netty/blob/netty-4.1.34.Final/transport-native-unix-common/src/main/java/io/netty/channel/unix/UnixChannelOption.java

These minor library resolution differences are somewhat expected when we swapped out Ivy, and we'd all have to adjust to it.

**Comment by dwijnand** [comment]
I suggest sbt 1.3 (or coursier) provides a way that allows users to upgrade sbt without also having to upgrade their dependency graph, such as with some option.

**Comment by eed3si9n** [comment]
The option would be 

```scala
ThisBuild / useCoursier := false
Global / cancelable := false
```

if you want to use existing older Play + sbt 1.3.0.

It's not ideal, but I don't think it's too bad to tell ppl to bump to latest 2.7.x if they want to use sbt 1.3.

**Comment by dwijnand** [comment]
Perhaps the sbt 1.3 release notes should include that information for Play users, then.

If we cut releases of Play 2.7 and 2.6 (the two stable versions) with the change for this before sbt 1.3, then it could also include the versions of Play that don't require disabling sbt's use of Coursier.

**Comment by eed3si9n** [comment]
> Perhaps the sbt 1.3 release notes should include that information for Play users, then.
>
> If we cut releases of Play 2.7 and 2.6 (the two stable versions) with the change for this before sbt 1.3, then it could also include the versions of Play that don't require disabling sbt's use of Coursier.

Sounds good. I am closing this issue for now then.

**Comment by dwijnand** [comment]
See @avdv's comment in https://github.com/playframework/playframework/pull/9416#issuecomment-506019981 - this has been misdiagnosed.

**Comment by eatkins** [comment]
So really the question here is why does the project not resolve correctly on travis? If I run `show Test / dependencyClasspath` on my local checkout of the play sample project, I see
```
[info] * Attributed(/Users/ethanatkins/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.1.34.Final/netty-transport-native-unix-common-4.1.34.Final.jar)
```
so coursier clearly is capable of resolving this jar.

**Comment by reibitto** [comment]
That's the same thing I'm wondering.

Also, it's not just Travis specifically. I originally ran into this error using Jenkins.

I only found this thread recently. I've been struggling to find out why it's behaving differently in a CI environment.

**Comment by eatkins** [comment]
@alexarchambault do you have any insight into what could be going wrong here? It seems like coursier produces different resolution results in different environments.

**Comment by avdv** [comment]
AFAIU [Maven Profiles](https://maven.apache.org/guides/introduction/introduction-to-profiles.html), this is only used when building a project, not when resolving dependencies (ie. after publishing). So there is really no magic there looking at a POM in Maven Central, the dependencies are simply the dependencies in `//project/dependencies`.

I see that Coursier has [some code](https://github.com/coursier/coursier/blob/6d0e24205a6c8d3ecf2c0d4674984a4366b1cd59/modules/tests/shared/src/test/scala/coursier/test/PomParsingTests.scala) to handle profiles in some way, which seems fishy.

**Comment by alexarchambault** [comment]
@eatkins Yes, coursier sometimes enables profiles based on the local OS and JDK version (profiles themselves turned out to be useful in some contexts, to pull more specific spark dependencies for example, via its `mesos`, `hadoop-X.Y`, …, profiles, to get less spurious metadata, like in the case of `javax.ws.rs:javax.ws.rs-api:2.1.1`, that has a wrong packaging type without profiles, and also to pull OS-specific JARs for some dependencies).

In the case here, a linux-specific profile was enabled in `io.netty:netty-transport-native-epoll`, but then a bug made it (spuriously) mark `io.netty:netty-transport-native-unix-common` from it as optional. https://github.com/coursier/coursier/pull/1239 should fix that.
