### ISSUE TITLE
ScriptMain doesn't work with Scala 2.13.3

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt#5664]
## steps

```scala
#!/usr/bin/env sbt -Dsbt.version=1.3.13 -Dsbt.main.class=sbt.ScriptMain

/***
scalaVersion := "2.13.3"
*/

println("hi there")
```

when I run this script I get:

```
% ./foo
[error] Error while emitting .scala
[error] String index out of range: 0
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## expectation

I expect the script to work, as it does when I change the `scalaVersion` line to 2.13.2

```
~/Desktop % ./foo
hi there
```

**Comment by SethTisue** [comment]
The error message is coming from `scala.tools.nsc.backend.jvm`

The problem goes away if you name the script `foo.scala` rather than `foo`

**Comment by SethTisue** [comment]
LOL:

```
% java -Dsbt.main.class=sbt.ScriptMain -jar sbt-launch.jar foo  
hi there
% java -Dsbt.main.class=sbt.ScriptMain -jar sbt-launch.jar ./foo
[error] Error while emitting .scala
[error] String index out of range: 0
```

**Comment by SethTisue** [comment]
`git bisect` identifies scala/scala#8564 as the PR where this regressed, specifically https://github.com/scala/scala/pull/8564/commits/8990489f609f74f7e79e49527dfdf7d5a37a9a08. hello @som-snytt

**Comment by SethTisue** [comment]
@som-snytt is it obvious to you at this point what the problem is, or should I keep digging? ⛏️

**Comment by som-snytt** [comment]
I don't know what `ScriptMain` is, but I could learn. The latest scala ticket had a compiler plugin creating an output dir `foo.jar`, so anything is possible.

**Comment by SethTisue** [comment]
I'll keep digging

**Comment by som-snytt** [comment]
Yeah it's happier if you name the file `sbt5664.sc`.

Edit: sorry I missed that you already noticed that providing a suffix is a workaround.

**Comment by som-snytt** [comment]
OK I read the doc for sbt scripting. Now I'll look at the source.

**Comment by som-snytt** [comment]
It looks like the change requires `-Xscript`.

Otherwise it wraps as garbage
```
<module> object  extends scala.AnyRef {
```
In the script,
```
scalacOptions ++= Seq("-Xscript", "Main")
```
Normally, this enables
```
scala -save -Xscript Greeter foo
```
Where `Greeter` is the class name in foo.jar. There is unfortunate overlap with `-Xmain-class`, which otherwise specifies the main class for `-d foo.jar`.

**Comment by som-snytt** [comment]
Just to verify, it looks like `-Xscript` was set wrong, and now it is used. Defaulting to `Main` doesn't help this issue, but I'll open a ticket to do that.
```
SET -Xscript = Main BY USER to 
SET -bootclasspath = "" BY USER to /Users/andrew/workspace/scala/build/pack/lib/scala-library.jar
SET -classpath = . BY USER to /Users/andrew/.sbt/boot/3fc029151e9a6a0298a2/target/scala-2.13/classes
SET -encoding = UTF-8 BY USER to UTF-8
```

**Comment by som-snytt** [comment]
The linked Scala PR attempts to accommodate a null or empty -Xscript, using "Main" in that case.

We know that naming is a top-three problem, so why make people pick a name for -Xscript which is essentially arbitrary?

I only just noticed that the ticket dates to July 1. Sorry about that, @SethTisue. I hope it didn't spoil your holiday weekend. We ought to raise and resolve issues only over three-day holiday weekends. It would lend a deeper rhythm to the project lifecycle. See you at Halloween. I don't believe opening and closing tickets is permitted over the High Holy Days. Not sure about Día de la Raza.

**Comment by SethTisue** [comment]
> I hope it didn't spoil your holiday weekend

If I look at GitHub on a holiday weekend, it's my own damn fault!

**Comment by SethTisue** [comment]
Leaving the ticket open until https://github.com/scala/scala/pull/9188 is merged

**Comment by SethTisue** [comment]
That PR is merged. Anyone affected has multiple options here: downgrade to 2.13.2, use a 2.13.4 nightly, wait for 2.13.4 final, or use the `scalacOptions` based workaround above. So, closing.

**Comment by SethTisue** [comment]
works with 2.13.4, which is now out

**Comment by som-snytt** [comment]
> We ought to raise and resolve issues only over three-day holiday weekends.

U.S. Thanksgiving isn't until next week. Four days of turkey and open source. (Make that open sauce.)
