### PR TITLE
Fix #2611: Codacy issues

### LINKED ISSUE #2611: todo: Codacy issues on 1.0.x
Currently there are some issues reported by Codacy (https://www.codacy.com/app/eed3si9n/sbt/dashboard) on code style and error prone category.
I've excluded scripted directory, but if things get included back again, we can ignore them.

For example, Codacy says "Fatal exception is being caught" in main-command/src/main/scala/sbt/Watched.scala.

### PR DESCRIPTION
**Pull request by dwijnand**
There's a lot of false positives in Codacy, sadly. But I've fixed all the ones that are plausible to fix.

I actually pushed for some more dubious changes, just so they could be talked about here in review. I'm happy to rework or revert any change.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Travis reports and other compilation errors:

```
[error] /home/travis/build/sbt/sbt/main-settings/src/main/scala/sbt/std/InputConvert.scala:16: value WrapInitTaskName is not a member of object sbt.std.ParserInput
[error]       case ParserInput.WrapInitTaskName => Converted.Failure(in.pos, initTaskErrorMessage)
[error]                        ^
```

**Comment by eed3si9n** [comment]
> I actually pushed for some more dubious changes, just so they could be talked about here in review.

I'm not particularly good at spotting bad changes. Which ones do you feel are more dubious?

**Comment by dwijnand** [comment]
- the various places where I opted to use NonFatal.. are those all correct changes?
- the performance impact of using pattern matching over if/else's

I'll actually compile it locally now and get this building :)

**Comment by dwijnand** [comment]
All green. I'll fixup the commits and rebase after the initial review.

File: main-settings/src/main/scala/sbt/std/InputWrapper.scala [hunk 1]
```diff
@@ -182,12 +182,12 @@ object ParserInput {
       }
     }
 
-  private def wrapInputTask[T](c: Context)(tree: c.Tree, pos: c.Position) = {
+  private def wrapInputTask[T: c.WeakTypeTag](c: Context)(tree: c.Tree, pos: c.Position) = {
```
Comment (eed3si9n) [inline main-settings/src/main/scala/sbt/std/InputWrapper.scala:185]: So we're thread safe because 2.11? - http://docs.scala-lang.org/overviews/reflection/thread-safety.html

Comment (dwijnand) [inline main-settings/src/main/scala/sbt/std/InputWrapper.scala:185]: This is a fixup commit, to be folded into the original, faulty refactor. The original code already used WeakTypeTag, so there's no semantic change, see https://github.com/sbt/sbt/pull/2655/files#diff-407b2912ff3a899d0ed98050a9b91908R176.

**Comment by eed3si9n** [comment]
LGTM
