### ISSUE TITLE
[2.x] sbt-native-packager UniversalDeployPlugin does not work with sbt 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#9676]
## steps

108623f84804f42ddbcfce09260c7d30290dda2d

```diff
--- a/sbt-app/src/sbt-test/plugins/sbt-native-packager/build.sbt
+++ b/sbt-app/src/sbt-test/plugins/sbt-native-packager/build.sbt
@@ -2,6 +2,7 @@ ThisBuild / scalaVersion := "3.8.4"
 
 name := "hello"
 enablePlugins(JavaAppPackaging)
+enablePlugins(UniversalDeployPlugin)
```

```sh
sbt "scripted plugins/sbt-native-packager"
```

## problem

```
java.lang.NoClassDefFoundError: sbt/internal/librarymanagement/IvySbt$Module
	at com.typesafe.sbt.packager.SettingsHelper$.makeDeploymentSettings(SettingsHelper.scala:111)
	at com.typesafe.sbt.packager.universal.UniversalDeployPlugin$.projectSettings(UniversalPlugin.scala:181)
	at sbt.internal.AutoPluginCache.projectSettings$$anonfun$1(Load.scala:54)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:475)
	at sbt.internal.AutoPluginCache.projectSettings(Load.scala:54)
	at sbt.internal.Load$.autoPluginSettings$1$$anonfun$1(Load.scala:1265)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:608)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:622)
```

## notes

https://github.com/sbt/sbt-native-packager/blob/21102683653020db468806d9233903734385c7ac/src/main/scala/com/typesafe/sbt/packager/SettingsHelper.scala#L47-L50
