### ISSUE TITLE
Clean/recompile on every new sbt incarnation on Java 10

### ISSUE THREAD

**Issue by johanandren** [sbt/sbt#4372]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## problem
Can't say for sure, but, potentially appeared after we upgraded to 1.2.3 in the Akka project.

Whenever I start a new instance of sbt in the Akka project, and do something that triggers a compile, I get this error:

```
akka > akka-actor-typed-tests/compile
[info] Formatting 1 Scala source ProjectRef(uri("file:/Users/johan/Code/Lightbend/Akka/akka-master/"), "akka-actor")(compile) ...
[info] Compiling 9 Scala sources to /Users/johan/Code/Lightbend/Akka/akka-master/akka-actor/target/classes ...
[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
[error] one error found
[error] (akka-actor / Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 21 Sep 2018, 16:01:42
```

Doing a `clean` and then recompiling everything is a workaround. While I then have the sbt instance running incremental compilation works just fine as far as I can see.

Seems to only happen on Java 10 actually, if I switch to Java 8 it works as expected.

## expectation
That I didn't have to do a clean/recompile on each start

## notes
sbt version: 1.2.3
Java version: "10" 2018-03-20

**Comment by jvican** [comment]
> Seems to only happen on Java 10 actually, if I switch to Java 8 it works as expected.
  
What happens if you switch to Java 9? Could you please try it?
  
This looks like a zinc error, so we may need to fix it there.

**Comment by johanandren** [comment]
Verified that the same happens with Java 9 (9.0.4+11)

**Comment by helena** [comment]
Verified with AdoptOpenJDK 11

**Comment by jvican** [comment]
@eed3si9n Can we move to sbt/zinc? I can try to have a shot at this in ~ two weeks

**Comment by eed3si9n** [comment]
ok. Transferring sbt/sbt#4372 over to Zinc.
