### ISSUE TITLE
stable identifier required, but ``sbt.`package`.CrossVersion.Disabled`` found.

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4975]
## steps

Scala.JS build using sbt 1.3.0-RC4

```scala
  def scalaJSMapped(cross: CrossVersion): CrossVersion = cross match {
    case CrossVersion.Disabled =>
      CrossVersion.constant("sjs" + currentBinaryVersion)
    case cross: sbt.librarymanagement.Constant =>
      cross.withValue("sjs" + currentBinaryVersion + "_" + cross.value)
    case cross: CrossVersion.Binary =>
      cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
    case cross: CrossVersion.Full =>
      cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
  }
```

## problem

```
[error] /Users/eed3si9n/work/scala-js/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSCrossVersion.scala:34:23: stable identifier required, but sbt.`package`.CrossVersion.Disabled found.
[error]     case CrossVersion.Disabled =>
[error]                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## expectation

No errors.

## notes
 
- https://github.com/sbt/librarymanagement/pull/121 (https://github.com/sbt/librarymanagement/pull/103) added `final val Disabled = sbt.librarymanagement.Disabled` but it was just a companion object
- https://github.com/sbt/librarymanagement/pull/280 actually made it `final val Disabled = sbt.librarymanagement.Disabled()`, but this broke Cat's build.
   `[cats] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;`
- https://github.com/sbt/librarymanagement/pull/290 changed to `final def Disabled = sbt.librarymanagement.Disabled` and `object Disabled extends sbt.librarymanagement.Disabled`, but this broke Scala.JS as above.

**Comment by eed3si9n** [comment]
I guess try

```scala
final val Disabled = sbt.librarymanagement.Disabled
```

?
