### ISSUE TITLE
[1.3.0-RC1] Defaults.collectFiles no longer returns expected sources

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt#4681]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## environment:
```
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## steps

```
$ sbt new playframework/play-java-seed.g8
...
name [play-java-seed]: <enter>
organization [com.example]: <enter>
...
$ cd play-java-seed/
play-java-seed$ echo "sbt.version=1.3.0-RC1" > project/build.properties
play-java-seed$ sbt
[play-java-seed] $ compile
```

## problem

You should see following compiler error:
```
[info] Compiling 4 Scala sources and 2 Java sources to /tmp/zinc_check/play-java-seed/target/scala-2.12/classes ...
[error] /tmp/zinc_check/play-java-seed/app/controllers/HomeController.java:18:1: cannot find symbol
[error]   symbol:   class index
[error]   location: package views.html
[error] views.html.index
[error] (Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 6 s, completed May 15, 2019, 12:21:27 PM
```

## expectation

It should compile.
**It does compile with sbt 1.2.8!**

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@mkurz Thanks for the report!

**Comment by mkurz** [comment]
You are welcome! Let me know if you need more information.

**Comment by mkurz** [comment]
Also the scala seed project does not compile (`playframework/play-scala-seed.g8`), with a slightly different compiler error:
```
[info] Compiling 5 Scala sources and 1 Java source to /tmp/zinc_check/play-scala-seed/target/scala-2.12/classes ...
[error] /tmp/zinc_check/play-scala-seed/app/controllers/HomeController.scala:22:19: object index is not a member of package views.html
[error]     Ok(views.html.index())
[error]                   ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

@eed3si9n do you think this will be fixed before sbt 1.3.0 final?

**Comment by mkurz** [comment]
I guess the problem has something to do with how twirl _should_ compile the template files:

https://github.com/playframework/playframework/blob/9b88cd7b47f01c413710e8f8e67775d8d67f86d3/build.sbt#L85-L98

**Comment by eed3si9n** [comment]
I have to look into the details, but I think it makes sense to figure out what's going on and fix it before the final.

**Comment by limansky** [comment]
I'm not sure if I should submit another ticket, but when I tried to compile BeanPuree with sbt 1.3.0-RC1 I've got OutOfMemoryError:
```
java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
```
Everything works fine with 1.2.8.

Steps to reproduce:
1. get beanpuree https://github.com/limansky/beanpuree
2. set sbt version to 1.3.0-RC1
3. sbt
4. +test

**Comment by eed3si9n** [comment]
Maybe we should split the issues by the error message.

**Comment by eed3si9n** [comment]
Running twirl tests with sbt 1.3.0-RC1 - https://github.com/playframework/twirl/pull/215

**Comment by eed3si9n** [comment]
I looked at Twirl a bit but I don't think there's a problem with Twirl itself with sbt 1.3.0-RC1. scripted etc passes. So that leaves Play.

**Comment by eed3si9n** [comment]
Actually it seems like the problem might be `SbtTwirl` + sbt 1.3.0-RC1.

Using sbt 1.2.8:

```
sbt:Play-Framework> show Routes-Compiler/Compile/twirlCompileTemplates/sources
[info] * /Users/eed3si9n/work/playframework/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
[info] * /Users/eed3si9n/work/playframework/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/routesPrefix.scala.twirl
[info] * /Users/eed3si9n/work/playframework/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javascriptReverseRouter.scala.twirl
[info] * /Users/eed3si9n/work/playframework/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl
[info] * /Users/eed3si9n/work/playframework/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl
```

using sbt 1.3.0-RC1:

```
sbt:Play-Framework> show Routes-Compiler/compile:twirlCompileTemplates::sources
[info] *
```

so that might be a regression on something related to

```scala
  def twirlSettings: Seq[Setting[_]] = SbtTwirlCompat.watchSourcesSettings ++ Seq(
    includeFilter in compileTemplates := "*.scala.*",
    excludeFilter in compileTemplates := HiddenFileFilter,
    sourceDirectories in compileTemplates := Seq(sourceDirectory.value / "twirl"),

    sources in compileTemplates := Defaults.collectFiles(
      sourceDirectories in compileTemplates,
      includeFilter in compileTemplates,
      excludeFilter in compileTemplates
    ).value,
```

**Comment by eed3si9n** [comment]
sbt itself doesn't use it, but lots of plugins do. We should add a scripted test - https://github.com/search?l=Scala&p=1&q=%22Defaults.collectFiles%22&type=Code
