### ISSUE TITLE
Tuples of TaskKey / SettingKey of 12 or greater lack 'map' method

### ISSUE THREAD

**Issue by LeifWarner** [sbt/sbt#857]
This worked on SBT 0.12.4:
https://github.com/flyway/flyway/blob/master/flyway-sbt-plugin/src/main/scala/com/googlecode/flyway/sbt/FlywayPlugin.scala#L116
On SBT 0.13.0:

```
 value map is not a member of (sbt.TaskKey[sbt.Keys.Classpath], sbt.TaskKey[sbt.Keys.TaskStreams], ...)
```

Did some experimentation: it seems to work as long as there are less than twelve keys tupled together.

**Comment by LeifWarner** [comment]
Found some relevant-looking commits, like:
https://github.com/sbt/sbt/commit/07fd9ab57e629e2ce32dda982c7488990c92d12e
But then 12 and above are commented out. In the case of this plugin, the location I linked to has a tuple size of 15.

**Comment by harrah** [comment]
This is indeed a regression since the claim was that the old syntax would still be supported in 0.13 in as many cases as possible.  However, note that the new syntax supports an arbitrary number of inputs and if you are only targeting 0.13, you should use the new syntax.

**Comment by jsuereth** [comment]
SO, we're closing this as won't fix for two reasons:
1.  Sbt 1.0 will be using the 0.13 syntax as the core syntax.  While the old syntax may still stick around, it will no longer be supported, specifically, tuples > 9 just won't be supported at all as the new API should be able to handle them and be nicer.
2.  There is a workaround (migrate to new 0.13 syntax).

Sorry this hit you during your initial 0.12->0.13 push.  We try to avoid all of these as we possibly can and in the future this type of regression will be immediately fixed.
